import React, { Fragment, useMemo, useState } from 'react';
import { ArrowRightLeft, Download, Eye, FileText, Pencil, Plus, Search, Trash2 } from 'lucide-react';
import { useLocation, useNavigate } from 'react-router-dom';
import { BBVAActionMenu } from '../../componentsBBVATalent/BBVAActionMenu';
import { BBVAAlert } from '../../componentsBBVATalent/BBVAAlert';
import { BBVAPagination } from '../../componentsBBVATalent/BBVAPagination';
import { BBVASearchableSelect } from '../../componentsBBVATalent/BBVASearchableSelect';
import { BBVATableSortHeader } from '../../componentsBBVATalent/BBVATableSortHeader';
import { TalentStageBadge } from '../../componentsBBVATalent/TalentStageBadge';
import { talentApi } from '../api/talentApi';
import { useCatalogOptions } from '../hooks/useCatalog';
import { useBBVAListMemory } from '../hooks/useBBVAListMemory';
import { useTalentList } from '../hooks/useTalent';
import { displayEmail, sentenceCaseData, upperIdentity } from '../lib/bbvaDisplayFormat';
import { downloadCvDocument, viewCvDocument } from '../lib/talentCv';
import { roleDisplay, technologyDisplay } from '../lib/talentDisplay';
import { TALENT_AFFILIATION_LABELS, TALENT_TYPE_LABELS, type Talent, type TalentAffiliation } from '../types/talent';

type TypeFilter='ALL'|'ACADEMY'|'PROSPECT'|'FORMER_COLLABORATOR';
type StatusFilter='ACTIVE'|'DELETED'|'ALL';
type AffiliationFilter='ALL'|TalentAffiliation;
type SortField='urgency'|'name'|'affiliation'|'status'|'origin'|'profile'|'technology'|'days';
const defaults={search:'',typeFilter:'ALL' as TypeFilter,affiliationFilter:'ALL' as AffiliationFilter,statusFilter:'ACTIVE' as StatusFilter,profileFilter:'ALL',technologyFilter:'ALL',structure2Filter:'ALL',structure3Filter:'ALL',page:0,size:10,sort:'urgency' as SortField,direction:'desc' as 'asc'|'desc'};
const typeOptions=[{value:'ALL',label:'Todos los tipos'},{value:'ACADEMY',label:'Academia'},{value:'PROSPECT',label:'Prospecto'},{value:'FORMER_COLLABORATOR',label:'Excolaborador'}] as const;
const unique=(values:Array<string|null|undefined>)=>[...new Set(values.map((value)=>String(value??'').trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'es-MX',{sensitivity:'base'}));

export const TalentPage:React.FC=()=>{
  const listQuery=useTalentList(); const profilesQuery=useCatalogOptions('profiles'); const technologiesQuery=useCatalogOptions('technologies'); const navigate=useNavigate(); const location=useLocation();
  const memory=useBBVAListMemory('talent-bank',defaults);
  const {search,typeFilter,affiliationFilter,statusFilter,profileFilter,technologyFilter,structure2Filter,structure3Filter,page,size,sort,direction}=memory.state;
  const [actionError,setActionError]=useState<string|null>(null); const [expanded,setExpanded]=useState<string|null>(null); const message=(location.state as {message?:string}|null)?.message??null;
  const items=listQuery.data?.items??[];
  const structure2Options=useMemo(()=>unique(items.map((item)=>item.bbvaStructureLevel2)),[items]);
  const structure3Options=useMemo(()=>unique(items.map((item)=>item.bbvaStructureLevel3)),[items]);
  const filtered=useMemo(()=>{
    const term=search.trim().toLocaleLowerCase('es-MX');
    const rows=items.filter((item)=>{
      const normalizedType=item.talentType==='BBVA_EXIT'?'FORMER_COLLABORATOR':item.talentType;
      const values=[item.fullName,item.softtekEmail,item.bbvaEmail,item.email,item.softtekCode,item.bbvaUser,item.corporateUser,item.profile,item.technologyProfile,item.currentTechnology,item.expertise,item.lifecycleReasonName,item.bbvaStructureLevel2,item.bbvaStructureLevel3];
      return (!term||values.filter(Boolean).some((v)=>String(v).toLocaleLowerCase('es-MX').includes(term)))
        &&(typeFilter==='ALL'||normalizedType===typeFilter)
        &&(affiliationFilter==='ALL'||item.affiliationType===affiliationFilter)
        &&(statusFilter==='ALL'||item.recordStatus===statusFilter)
        &&(profileFilter==='ALL'||item.profileCatalogId===profileFilter)
        &&(technologyFilter==='ALL'||item.currentTechnologyCatalogId===technologyFilter)
        &&(structure2Filter==='ALL'||item.bbvaStructureLevel2===structure2Filter)
        &&(structure3Filter==='ALL'||item.bbvaStructureLevel3===structure3Filter);
    });
    const value=(item:Talent)=>sort==='urgency'?(item.urgentAssignment?1000000:0)+item.talentBankEntryCount*10000+item.daysInTalentBank:sort==='days'?item.daysInTalentBank:sort==='name'?item.fullName:sort==='affiliation'?TALENT_AFFILIATION_LABELS[item.affiliationType]:sort==='status'?(item.recordStatus==='DELETED'?'Eliminado':item.stage):sort==='origin'?(item.lifecycleReasonName||TALENT_TYPE_LABELS[item.talentType]):sort==='profile'?roleDisplay(item):technologyDisplay(item);
    return rows.sort((a,b)=>{const av=value(a),bv=value(b);const c=typeof av==='number'&&typeof bv==='number'?av-bv:String(av??'').localeCompare(String(bv??''),'es-MX',{sensitivity:'base',numeric:true});return direction==='asc'?c:-c;});
  },[affiliationFilter,direction,items,profileFilter,search,sort,statusFilter,structure2Filter,structure3Filter,technologyFilter,typeFilter]);
  const safePage=Math.min(page,Math.max(0,Math.ceil(filtered.length/size)-1)); const paged=filtered.slice(safePage*size,safePage*size+size);
  const changeSort=(field:SortField)=>memory.patch(sort===field?{direction:direction==='asc'?'desc':'asc',page:0}:{sort:field,direction:field==='urgency'||field==='days'?'desc':'asc',page:0});
  const openCv=async(item:Talent,download:boolean)=>{try{setActionError(null);const r=await talentApi.getCv(item.id);if(download)downloadCvDocument(r.document);else viewCvDocument(r.document);}catch(e){setActionError((e as Error).message);}};
  return <div className="space-y-3 animate-fade-in">
    <div className="flex justify-end"><button type="button" onClick={()=>navigate('/bbva/talent-bank/new')} className="inline-flex h-8 items-center gap-1.5 rounded-md bg-blue-600 px-3 text-[11px] font-semibold text-white shadow-sm hover:bg-blue-500"><Plus className="h-3.5 w-3.5"/>Agregar talento</button></div>
    {message?<BBVAAlert tone="success" onClose={()=>navigate(location.pathname,{replace:true,state:{}})}>{message}</BBVAAlert>:null}{actionError?<BBVAAlert tone="error" onClose={()=>setActionError(null)}>{actionError}</BBVAAlert>:null}
    <div className="grid gap-2 xl:grid-cols-4 2xl:grid-cols-8">
      <div className="relative xl:col-span-2"><Search className="absolute left-2.5 top-2 h-3.5 w-3.5 text-slate-400"/><input value={search} onChange={(e)=>memory.patch({search:e.target.value,page:0})} placeholder="Buscar por nombre, correo o IS" className="h-8 w-full rounded-md border border-slate-300 bg-white py-1 pl-8 pr-2.5 text-[11px] outline-none focus:border-blue-500"/></div>
      <BBVASearchableSelect value={typeFilter} onChange={(v)=>memory.patch({typeFilter:v as TypeFilter,page:0})} options={[...typeOptions]} ariaLabel="Tipo"/>
      <BBVASearchableSelect value={statusFilter} onChange={(v)=>memory.patch({statusFilter:v as StatusFilter,page:0})} options={[{value:'ACTIVE',label:'Activos'},{value:'DELETED',label:'Eliminados'},{value:'ALL',label:'Todos'}]} ariaLabel="Estado"/>
      <BBVASearchableSelect value={technologyFilter} onChange={(v)=>memory.patch({technologyFilter:v,page:0})} options={[{value:'ALL',label:'Todas las tecnologías'},...(technologiesQuery.data?.items??[]).map((o)=>({value:o.id,label:sentenceCaseData(o.name)}))]} ariaLabel="Tecnología"/>
      <BBVASearchableSelect value={structure2Filter} onChange={(v)=>memory.patch({structure2Filter:v,page:0})} options={[{value:'ALL',label:'Estructura nivel 2'},...structure2Options.map((value)=>({value,label:sentenceCaseData(value)}))]} ariaLabel="Estructura nivel 2"/>
      <BBVASearchableSelect value={structure3Filter} onChange={(v)=>memory.patch({structure3Filter:v,page:0})} options={[{value:'ALL',label:'Estructura nivel 3'},...structure3Options.map((value)=>({value,label:sentenceCaseData(value)}))]} ariaLabel="Estructura nivel 3"/>
      <BBVASearchableSelect value={affiliationFilter} onChange={(v)=>memory.patch({affiliationFilter:v as AffiliationFilter,page:0})} options={[{value:'ALL',label:'Internos y externos'},{value:'INTERNAL',label:'Internos'},{value:'EXTERNAL',label:'Externos'}]} ariaLabel="Vinculación"/>
      <div className="hidden"><BBVASearchableSelect value={profileFilter} onChange={(v)=>memory.patch({profileFilter:v,page:0})} options={[{value:'ALL',label:'Todos los perfiles'},...(profilesQuery.data?.items??[]).map((o)=>({value:o.id,label:sentenceCaseData(o.name)}))]} ariaLabel="Perfil"/></div>
    </div>
    {listQuery.isLoading?<div className="rounded-lg border border-slate-200 bg-white p-8 text-center text-xs text-slate-500">Cargando Banco de talento...</div>:listQuery.error?<BBVAAlert tone="error">{(listQuery.error as Error).message}</BBVAAlert>:<div className="overflow-visible rounded-lg border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[1460px] table-fixed text-left text-[10.5px]"><thead className="border-b border-slate-200 bg-slate-50/90 text-[9px] font-semibold uppercase text-slate-600"><tr>
      <th className="w-[17%] px-2 py-1.5"><BBVATableSortHeader label="Persona" active={sort==='name'} direction={direction} onClick={()=>changeSort('name')}/></th><th className="w-[8%] px-2 py-1.5"><BBVATableSortHeader label="Vinculación" active={sort==='affiliation'} direction={direction} onClick={()=>changeSort('affiliation')}/></th><th className="w-[10%] px-2 py-1.5"><BBVATableSortHeader label="Estatus" active={sort==='status'} direction={direction} onClick={()=>changeSort('status')}/></th><th className="w-[13%] px-2 py-1.5"><BBVATableSortHeader label="Motivo / origen" active={sort==='origin'} direction={direction} onClick={()=>changeSort('origin')}/></th><th className="w-[15%] px-2 py-1.5"><BBVATableSortHeader label="Perfil" active={sort==='profile'} direction={direction} onClick={()=>changeSort('profile')}/></th><th className="w-[10%] px-2 py-1.5"><BBVATableSortHeader label="Tecnología" active={sort==='technology'} direction={direction} onClick={()=>changeSort('technology')}/></th><th className="w-[13%] px-2 py-1.5">Estructura BBVA</th><th className="w-[9%] px-2 py-1.5"><BBVATableSortHeader label="Permanencia" active={sort==='days'||sort==='urgency'} direction={direction} onClick={()=>changeSort('urgency')}/></th><th className="w-[5%] px-2 py-1.5 text-right">Acciones</th>
    </tr></thead><tbody className="divide-y divide-slate-200">{paged.map((item)=>{const deleted=item.recordStatus==='DELETED';const isExpanded=expanded===item.id;return <Fragment key={item.id}><tr className={`h-[46px] cursor-pointer transition hover:bg-blue-50/35 ${isExpanded?'bg-blue-50/45':''} ${item.urgentAssignment?'bg-amber-50/35 ring-1 ring-inset ring-amber-200':''} ${deleted?'opacity-70':''}`} onClick={()=>setExpanded(isExpanded?null:item.id)} onKeyDown={(event)=>{if(event.target!==event.currentTarget)return;if(event.key==='Enter'||event.key===' '){event.preventDefault();setExpanded(isExpanded?null:item.id);}}} tabIndex={0} aria-expanded={isExpanded} title="Clic para ver contexto de Banco de talento">
      <td className="px-2 py-1.5"><div className="truncate font-semibold text-slate-900">{sentenceCaseData(item.fullName)}</div><div className="truncate text-[9.5px] text-slate-500">{item.softtekEmail||item.email}</div></td><td className="px-2 py-1.5"><span className="rounded-full bg-slate-100 px-2 py-1 text-[9.5px] font-semibold text-slate-700">{sentenceCaseData(TALENT_AFFILIATION_LABELS[item.affiliationType])}</span></td><td className="px-2 py-1.5">{deleted?<span className="rounded-full bg-rose-50 px-2 py-1 text-[9.5px] font-semibold text-rose-700">Eliminado</span>:<TalentStageBadge stage={item.stage}/>}</td><td className="px-2 py-1.5"><div className="truncate font-medium text-slate-700">{sentenceCaseData(item.lifecycleReasonName||TALENT_TYPE_LABELS[item.talentType])}</div></td><td className="px-2 py-1.5 text-slate-700"><div className="line-clamp-2">{sentenceCaseData(roleDisplay(item))}</div></td><td className="px-2 py-1.5 text-slate-700">{sentenceCaseData(technologyDisplay(item))}</td><td className="px-2 py-1.5"><div className="truncate font-medium text-slate-700">{sentenceCaseData(item.bbvaStructureLevel2)}</div><div className="truncate text-[9px] text-slate-400">{sentenceCaseData(item.bbvaStructureLevel3)}</div></td><td className="px-2 py-1.5"><div className="font-semibold tabular-nums text-slate-800">{item.daysInTalentBank} días</div><div className="text-[9px] text-slate-500">{item.talentBankEntryCount} {item.talentBankEntryCount===1?'entrada':'entradas'}</div>{item.urgentAssignment?<span className="mt-1 inline-flex rounded-full bg-rose-100 px-2 py-0.5 text-[8px] font-bold text-rose-700">Urgente de asignar</span>:null}</td><td className="px-2 py-1.5 text-right" onClick={(e)=>e.stopPropagation()} onKeyDown={(e)=>e.stopPropagation()}><BBVAActionMenu items={[{id:'view',label:'Ver',icon:Eye,onClick:()=>navigate(`/bbva/talent-bank/${item.id}`)},{id:'edit',label:'Editar',icon:Pencil,disabled:deleted,onClick:()=>navigate(`/bbva/talent-bank/${item.id}/edit`)},{id:'convert',label:'Convertir a colaborador',icon:ArrowRightLeft,disabled:deleted,onClick:()=>navigate(`/bbva/talent-bank/${item.id}/convert`)},{id:'view-cv',label:'Ver CV',icon:FileText,disabled:!item.cv,onClick:()=>void openCv(item,false)},{id:'download-cv',label:'Descargar CV',icon:Download,disabled:!item.cv,onClick:()=>void openCv(item,true)},{id:'delete',label:'Eliminar',icon:Trash2,tone:'danger',disabled:deleted,onClick:()=>navigate(`/bbva/talent-bank/${item.id}/delete`)}]}/></td></tr>
      {isExpanded?<tr className="bg-slate-50/75"><td colSpan={9} className="px-3 py-3"><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-4 xl:grid-cols-11"><div><div className="text-[8px] font-semibold uppercase tracking-[.05em] text-slate-400">IS Softtek</div><div className="mt-1 text-[10px] font-semibold text-slate-700">{upperIdentity(item.softtekCode)}</div></div><div><div className="text-[8px] font-semibold uppercase tracking-[.05em] text-slate-400">Usuario BBVA / XM</div><div className="mt-1 text-[10px] font-semibold text-slate-700">{upperIdentity(item.bbvaUser||item.corporateUser)}</div></div><div><div className="text-[8px] font-semibold uppercase tracking-[.05em] text-slate-400">Correo Softtek</div><div className="mt-1 truncate text-[10px] font-semibold text-slate-700">{displayEmail(item.softtekEmail||item.email)}</div></div><div><div className="text-[8px] font-semibold uppercase tracking-[.05em] text-slate-400">Correo BBVA</div><div className="mt-1 truncate text-[10px] font-semibold text-slate-700">{displayEmail(item.bbvaEmail)}</div></div><div><div className="text-[8px] font-semibold uppercase tracking-[.05em] text-slate-400">Estructura nivel 2</div><div className="mt-1 text-[10px] font-semibold text-slate-700">{sentenceCaseData(item.bbvaStructureLevel2)}</div></div><div><div className="text-[8px] font-semibold uppercase tracking-[.05em] text-slate-400">Estructura nivel 3</div><div className="mt-1 text-[10px] font-semibold text-slate-700">{sentenceCaseData(item.bbvaStructureLevel3)}</div></div><div><div className="text-[8px] font-semibold uppercase tracking-[.05em] text-slate-400">Perfil tecnológico</div><div className="mt-1 text-[10px] font-semibold text-slate-700">{sentenceCaseData(item.technologyProfile)}</div></div><div><div className="text-[8px] font-semibold uppercase tracking-[.05em] text-slate-400">Tecnología actual</div><div className="mt-1 text-[10px] font-semibold text-slate-700">{sentenceCaseData(item.currentTechnology)}</div></div><div><div className="text-[8px] font-semibold uppercase tracking-[.05em] text-slate-400">Días en Banco</div><div className="mt-1 text-[10px] font-semibold text-slate-700">{item.daysInTalentBank}</div></div><div><div className="text-[8px] font-semibold uppercase tracking-[.05em] text-slate-400">Entradas históricas</div><div className="mt-1 text-[10px] font-semibold text-slate-700">{item.talentBankEntryCount}</div></div><div><div className="text-[8px] font-semibold uppercase tracking-[.05em] text-slate-400">CV</div><div className="mt-1 truncate text-[10px] font-semibold text-slate-700">{sentenceCaseData(item.cv?.fileName)}</div></div></div></td></tr>:null}</Fragment>;})}</tbody></table></div>{filtered.length===0?<div className="p-8 text-center text-xs text-slate-500">No hay registros que coincidan con los filtros.</div>:<BBVAPagination total={filtered.length} page={safePage} size={size} onPageChange={(v)=>memory.patch({page:v})} onSizeChange={(v)=>memory.patch({size:v,page:0})}/>}</div>}
  </div>;
};
