import { fetchApi } from '../../lib/api';
import type { CollaboratorCertification, CollaboratorCertificationDetail, CollaboratorCertificationSummary, CertificationAttemptResult, CertificationTrackingItem, CertificationCommunication, CertificationCriticalResolutionPayload } from '../types/collaboratorCertification';

export const collaboratorCertificationApi = {
  tracking: () => fetchApi<{ items: CertificationTrackingItem[]; vendorQuarter: { calendarName:string; currentCode:string|null; targetCode:string|null; targetStartDate:string|null; targetEndDate:string|null; daysToTargetStart:number|null; pendingCertifications:number; exhaustedAttempts:number; referenceDate:string; years:number[]; quarters:Array<{code:string;year:number;quarter:1|2|3|4;startDate:string;endDate:string}> } }>('/bbva/certifications/tracking-items'),
  list: (collaboratorId: string) => fetchApi<{ items: CollaboratorCertification[]; summary: CollaboratorCertificationSummary }>(`/bbva/collaborators/${collaboratorId}/certifications`),
  get: (collaboratorId: string, recordId: string) => fetchApi<CollaboratorCertificationDetail>(`/bbva/collaborators/${collaboratorId}/certifications/${recordId}`),
  add: (collaboratorId: string, certificationId: string, certificationLevel?: string) => fetchApi<{ item: CollaboratorCertification }>(`/bbva/collaborators/${collaboratorId}/certifications`, { method: 'POST', body: JSON.stringify({ certificationId, certificationLevel }) }),
  update: (collaboratorId: string, recordId: string, payload: { scheduledDate: string; notes: string; mandatory: boolean }) => fetchApi<{ item: CollaboratorCertification }>(`/bbva/collaborators/${collaboratorId}/certifications/${recordId}`, { method: 'PUT', body: JSON.stringify(payload) }),
  updateCoverage: (collaboratorId: string, recordId: string, payload: { memberRecordIds: string[] }) => fetchApi<{ item: CollaboratorCertification }>(`/bbva/collaborators/${collaboratorId}/certifications/${recordId}/coverage`, { method: 'PUT', body: JSON.stringify(payload) }),
  addAttempt: (collaboratorId: string, recordId: string, payload: { applicationDate: string; result: CertificationAttemptResult; score10: number | null; notes: string }) => fetchApi<CollaboratorCertificationDetail>(`/bbva/collaborators/${collaboratorId}/certifications/${recordId}/attempts`, { method: 'POST', body: JSON.stringify(payload) }),
  updateAttempt: (collaboratorId:string,recordId:string,attemptId:string,payload:{applicationDate:string;result:CertificationAttemptResult;score10:number|null;attemptNumber:number;notes:string}) => fetchApi<CollaboratorCertificationDetail>(`/bbva/collaborators/${collaboratorId}/certifications/${recordId}/attempts/${attemptId}`,{method:'PUT',body:JSON.stringify(payload)}),
  resolveCritical: (collaboratorId: string, recordId: string, payload: CertificationCriticalResolutionPayload) => fetchApi<{ item: CollaboratorCertification }>(`/bbva/collaborators/${collaboratorId}/certifications/${recordId}/critical-resolution`, { method: 'POST', body: JSON.stringify(payload) }),
  recertify: (collaboratorId: string, recordId: string) => fetchApi<{ item: CollaboratorCertification }>(`/bbva/collaborators/${collaboratorId}/certifications/${recordId}/recertify`, { method: 'POST' }),
  generateCommunication: (collaboratorId: string, recordId: string, attemptId: string, regenerate = false) => fetchApi<{ item: CertificationCommunication }>(`/bbva/collaborators/${collaboratorId}/certifications/${recordId}/communications`, { method: 'POST', body: JSON.stringify({ attemptId, regenerate }) }),
  prepareCommunicationEmail: (collaboratorId: string, recordId: string, communicationId: string, payload: { subject?: string; body?: string }) => fetchApi<{ item: CertificationCommunication }>(`/bbva/collaborators/${collaboratorId}/certifications/${recordId}/communications/${communicationId}/email`, { method: 'POST', body: JSON.stringify(payload) }),
  markNotApplicable: (collaboratorId: string, recordId: string) => fetchApi<{ item: CollaboratorCertification }>(`/bbva/collaborators/${collaboratorId}/certifications/${recordId}`, { method: 'DELETE' }),
};
