import React, { useState } from 'react';
import { Pencil, Plus, Power, RefreshCw, Search, Trash2, UserRoundCog } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { BBVAActionMenu } from '../../componentsBBVATalent/BBVAActionMenu';
import { BBVAAlert } from '../../componentsBBVATalent/BBVAAlert';
import { BBVAPagination } from '../../componentsBBVATalent/BBVAPagination';
import { BBVAFilterBar } from '../../componentsBBVATalent/BBVAFilterBar';
import { BBVASearchableSelect } from '../../componentsBBVATalent/BBVASearchableSelect';
import { ConfirmDialog } from '../../componentsBBVATalent/ConfirmDialog';
import { useAdminUsers, useDeleteAdminUser, useUpdateAdminUserStatus } from '../hooks/useAdminUsers';
import { upperDisplay, upperIdentity } from '../lib/bbvaDisplayFormat';
import type { AdminStatus, AdminUser } from '../types/adminUser';

const roleInitials=(name:string)=>{const words=String(name??'').trim().split(/\s+/).filter(Boolean);if(!words.length)return '—';return (words.length>1?words.slice(0,2).map((word)=>word.charAt(0)).join(''):words[0].slice(0,2)).toLocaleUpperCase('es-MX');};

export const AdminUsersPage: React.FC = () => {
  const navigate=useNavigate(); const [search,setSearch]=useState(''); const [status,setStatus]=useState<AdminStatus|'ALL'>('ACTIVE'); const [page,setPage]=useState(0); const [size,setSize]=useState(10); const [pending,setPending]=useState<{kind:'status'|'delete';item:AdminUser;status?:AdminStatus}|null>(null); const [error,setError]=useState<string|null>(null);
  const query=useAdminUsers({search,status,page,size}); const statusMutation=useUpdateAdminUserStatus(); const deleteMutation=useDeleteAdminUser();
  const confirm=async()=>{if(!pending)return;try{setError(null);if(pending.kind==='delete')await deleteMutation.mutateAsync(pending.item.id);else await statusMutation.mutateAsync({id:pending.item.id,status:pending.status!});setPending(null);}catch(e){setError((e as Error).message);}};
  return <div className="space-y-3 animate-fade-in">
    <div className="flex justify-end"><button type="button" onClick={()=>navigate('/bbva/admin/users/new')} className="inline-flex h-9 items-center gap-2 rounded-xl bg-blue-600 px-4 text-[11px] font-semibold text-white"><Plus className="h-4 w-4"/>Nuevo usuario</button></div>
    {error?<BBVAAlert tone="error" onClose={()=>setError(null)}>{error}</BBVAAlert>:null}
    <BBVAFilterBar><div className="relative w-full sm:w-[320px]"><Search className="absolute left-3 top-2.5 h-4 w-4 text-slate-400"/><input value={search} onChange={(e)=>{setSearch(e.target.value);setPage(0);}} placeholder="Buscar por nombre, correo, XM o IS" className="h-9 w-full rounded-xl border border-slate-300 pl-9 pr-3 text-[11px] text-slate-900 outline-none focus:border-blue-500"/></div><div className="w-full sm:w-[180px]"><BBVASearchableSelect value={status} onChange={(v)=>{setStatus(v as AdminStatus|'ALL');setPage(0);}} options={[{value:'ACTIVE',label:'Activos'},{value:'INACTIVE',label:'Inactivos'},{value:'ALL',label:'Todos'}]} ariaLabel="Estado de usuarios"/></div></BBVAFilterBar>
    {query.error?<BBVAAlert tone="error">{(query.error as Error).message}</BBVAAlert>:<div className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-[10.5px]"><thead className="bg-slate-50 text-[8.5px] font-semibold uppercase tracking-[.04em] text-slate-500"><tr><th className="px-3 py-2">Usuario</th><th className="px-3 py-2">Identidad</th><th className="px-3 py-2">Roles</th><th className="px-3 py-2 text-center">Colaboradores</th><th className="px-3 py-2">Estado</th><th className="px-3 py-2 text-right">Acciones</th></tr></thead><tbody className="divide-y divide-slate-100">{(query.data?.items??[]).map((item)=><tr key={item.id} className="hover:bg-slate-50"><td className="px-3 py-2"><div className="font-semibold text-slate-900">{upperDisplay(item.fullName)}</div><div className="text-[9px] text-slate-400">{item.email||'Sin correo registrado'}</div></td><td className="px-3 py-2 text-slate-600"><div>{upperIdentity(item.corporateUser,'—')}</div><div className="text-[9px] text-slate-400">IS {upperIdentity(item.softtekCode,'—')}</div></td><td className="px-3 py-2"><div className="flex flex-wrap gap-1">{item.roles.map((r)=><span key={r.id} className={`rounded-full px-2 py-0.5 text-[8px] font-semibold ${r.isDeliveryManager?'bg-blue-50 text-blue-700':'bg-slate-100 text-slate-600'}`}>{roleInitials(r.name)}</span>)}</div></td><td className="px-3 py-2 text-center font-semibold tabular-nums">{item.collaboratorCount}</td><td className="px-3 py-2"><span className={`rounded-full px-2 py-0.5 text-[8px] font-semibold ${item.status==='ACTIVE'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-500'}`}>{item.status==='ACTIVE'?'Activo':'Inactivo'}</span></td><td className="px-3 py-2 text-right"><BBVAActionMenu items={[{id:'edit',label:'Editar',icon:Pencil,onClick:()=>navigate(`/bbva/admin/users/${item.id}/edit`)},item.status==='ACTIVE'?{id:'off',label:'Inactivar',icon:Power,onClick:()=>setPending({kind:'status',item,status:'INACTIVE'})}:{id:'on',label:'Activar',icon:RefreshCw,onClick:()=>setPending({kind:'status',item,status:'ACTIVE'})},{id:'delete',label:'Eliminar',icon:Trash2,tone:'danger' as const,onClick:()=>setPending({kind:'delete',item})}]}/></td></tr>)}</tbody></table></div>{!query.isLoading&&(query.data?.total??0)===0?<div className="p-10 text-center"><UserRoundCog className="mx-auto h-6 w-6 text-slate-300"/><div className="mt-2 text-[11px] text-slate-500">No hay usuarios con estos filtros.</div></div>:<BBVAPagination total={query.data?.total??0} page={page} size={size} onPageChange={setPage} onSizeChange={(v)=>{setSize(v);setPage(0);}}/>}</div>}
    <ConfirmDialog open={Boolean(pending)} title={pending?.kind==='delete'?'Eliminar usuario':pending?.status==='ACTIVE'?'Activar usuario':'Inactivar usuario'} message={pending?.kind==='delete'?`Se eliminará “${pending.item.fullName}” si no tiene asignaciones vigentes.`:`Se ${pending?.status==='ACTIVE'?'activará':'inactivará'} “${pending?.item.fullName??''}”.`} confirmLabel={pending?.kind==='delete'?'Eliminar':pending?.status==='ACTIVE'?'Activar':'Inactivar'} tone={pending?.kind==='delete'?'danger':'warning'} busy={statusMutation.isPending||deleteMutation.isPending} onCancel={()=>setPending(null)} onConfirm={()=>void confirm()}/>
  </div>;
};
