SET NOCOUNT ON;
SET XACT_ABORT ON;
BEGIN TRY
  BEGIN TRANSACTION;
  IF SCHEMA_ID(N'bbva') IS NULL EXEC(N'CREATE SCHEMA bbva');
  IF OBJECT_ID(N'bbva.EngineeringSpecialtyCatalog',N'U') IS NULL
  BEGIN
    CREATE TABLE bbva.EngineeringSpecialtyCatalog(
      Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_BBVA_EngineeringSpecialtyCatalog PRIMARY KEY DEFAULT NEWID(),
      N3 NVARCHAR(180) NOT NULL,Guild NVARCHAR(220) NOT NULL,Specialty NVARCHAR(220) NOT NULL,
      GuildLeader NVARCHAR(220) NULL,SpecialtyOwner NVARCHAR(220) NULL,PortfolioStaffing NVARCHAR(220) NULL,Staffer NVARCHAR(220) NULL,
      Status NVARCHAR(16) NOT NULL CONSTRAINT DF_BBVA_EngineeringSpecialty_Status DEFAULT N'ACTIVE',
      CreatedAt DATETIME2(7) NOT NULL CONSTRAINT DF_BBVA_EngineeringSpecialty_CreatedAt DEFAULT SYSUTCDATETIME(),
      UpdatedAt DATETIME2(7) NOT NULL CONSTRAINT DF_BBVA_EngineeringSpecialty_UpdatedAt DEFAULT SYSUTCDATETIME(),
      CreatedByEmail NVARCHAR(320) NOT NULL,UpdatedByEmail NVARCHAR(320) NOT NULL,
      CONSTRAINT CK_BBVA_EngineeringSpecialty_Status CHECK(Status IN(N'ACTIVE',N'INACTIVE',N'DELETED'))
    );
    CREATE UNIQUE INDEX UX_BBVA_EngineeringSpecialty_Hierarchy ON bbva.EngineeringSpecialtyCatalog(N3,Guild,Specialty);
    CREATE INDEX IX_BBVA_EngineeringSpecialty_Status ON bbva.EngineeringSpecialtyCatalog(Status,N3,Guild,Specialty);
  END;
  DECLARE @Seed TABLE(N3 NVARCHAR(180),Guild NVARCHAR(220),Specialty NVARCHAR(220),GuildLeader NVARCHAR(220),SpecialtyOwner NVARCHAR(220),PortfolioStaffing NVARCHAR(220),Staffer NVARCHAR(220));
  INSERT INTO @Seed(N3,Guild,Specialty,GuildLeader,SpecialtyOwner,PortfolioStaffing,Staffer) VALUES
      (N'[A] ARCHITECTURE',N'(A2) CHANNELS',N'(A2-2) BRANCHES ARCHITECTURE',N'FERNANDO DÍAZ GODOY',N'DANTE DOMINGUEZ RODIRGUEZ',N'ROBERTO DE JESUS SANCHÉZ PUEBLA',N'JESUS RAMOS VARGAS'),
      (N'[A] ARCHITECTURE',N'(A3) BACKEND ARCHITECTURE',N'(A3-1) WORKPLACE, NETWORKING & CLOUD',N'CARLOS AARON CASTILLO LECHUGA',N'BERENICE IVONNE URIBE GONZALEZ',N'ROBERTO DE JESUS SANCHÉZ PUEBLA',N'JESSICA IVONNE TELLEZ VARGAS'),
      (N'[A] ARCHITECTURE',N'(A4) INTELLIGENT AUTOMATION ARCHITECTURE',N'(A4-4) ARTIFICIAL INTELLIGENCE',N'ISAAC FLORES LIRA',N'CARLOS CARRILLO CERÓN',N'ROBERTO DE JESUS SANCHÉZ PUEBLA',N'NOÉ BARRERA GONZÁLEZ'),
      (N'[A] ARCHITECTURE',N'(A4) INTELLIGENT AUTOMATION ARCHITECTURE',N'(A4-5) AUTOMATION',N'ISAAC FLORES LIRA',N'MARCO ANTONIO BELMONT PARTIDA',N'ROBERTO DE JESUS SANCHÉZ PUEBLA',N'CHRISTIAN ALBERTO PALMA CASTRO'),
      (N'[A] ARCHITECTURE',N'(A8) ALPHA',N'(A8-1) ALPHA',N'GUSTAVO DIAZ OLVERA',N'BERENICE SANTACRUZ PORTILLO',N'ROBERTO DE JESUS SANCHÉZ PUEBLA',N'JOCELYN STEPHANIE ESQUIVEL GUTIÉRREZ'),
      (N'[B] BPE',N'(B3) POOL BPE',N'(B3-2) POOL BPE',N'ISRAEL MARTINEZ GUZMAN',N'ALMA ROSA ORTIZ',N'ISRAEL MARTINEZ GUZMAN',N'ALMA ROSA ORTIZ'),
      (N'[C] FINANCIAL CRIME PREVENTION',N'(C2) FCP STRATEGY PERFORMANCE & CONTROL',N'(C2-4) SOLUTIONS DEVELOPMENT',N'MONICA BEATRIZ TURCATO DELGADO',N'EDÉN MAYORGA RAMÍREZ',N'VIVIANA VALENCIA AYALA',N'TBD'),
      (N'[D] INFORMATION SECURITY',N'(D2) INFORMATION SECURITY - SOLUTIONS DEVELOPMENT',N'(D2-2) INFORMATION SECURITY SOLUTIONS I',N'CARMINA CECILIA ESPINOSA MADRIGAL',N'CARMINA CECILIA ESPINOSA',N'CARMINA CECILIA ESPINOSA',N'ALVARO GRANADOS NOBLE'),
      (N'[D] INFORMATION SECURITY',N'(D5) IAM',N'(D5-2) DATA SECURITY',N'RICARDO JOAQUIN CASTAÑEDA SIGLER',N'FREDY SANCHEZ HERNANDEZ',N'CARMINA CECILIA ESPINOSA',N'ALVARO GRANADOS NOBLE'),
      (N'[D] INFORMATION SECURITY',N'(D5) IAM',N'(D5-4) IAM PLATFORMS',N'RICARDO JOAQUIN CASTAÑEDA SIGLER',N'ALAN GUTIÉRREZ MARTÍNEZ',N'CARMINA CECILIA ESPINOSA',N'ALVARO GRANADOS NOBLE'),
      (N'[D] INFORMATION SECURITY',N'(D6) SECURITY ARCHITECTURE',N'(D6-3) SECURITY INNOVATION',N'MARCO ANTONIO LEON HIDALGO',N'ERIC ESPARZA GALINA',N'CARMINA CECILIA ESPINOSA',N'ALVARO GRANADOS NOBLE'),
      (N'[D] INFORMATION SECURITY',N'(D6) SECURITY ARCHITECTURE',N'(D6-4) DYD SECURITY',N'MARCO ANTONIO LEON HIDALGO',N'RAMON ALBERTO MORA REYES',N'CARMINA CECILIA ESPINOSA',N'ALVARO GRANADOS NOBLE'),
      (N'[G] DATA ENGINEERING',N'(G1) DATA MODELLING & DEVELOPMENT',N'(G1-2) DATA MODELLING',N'KAREN NARVÁEZ MELENDEZ',N'KAREN LOYA MARTIN',N'FABIOLA GUERRERO GUIDO',N'ANDREA TORRES DE LEON'),
      (N'[G] DATA ENGINEERING',N'(G2) DATA HUB - FINANCE & RISK',N'(G2-2) DATA HUB - FINANCE',N'DORA BERENICE CRUZ HERNÁNDEZ',N'FERNANDO GILBON GONZÁLEZ',N'FABIOLA GUERRERO GUIDO',N'ANDREA TORRES DE LEON'),
      (N'[G] DATA ENGINEERING',N'(G2) DATA HUB - FINANCE & RISK',N'(G2-3) DATA HUB - RISK',N'DORA BERENICE CRUZ HERNÁNDEZ',N'MARIBEL TELLEZ MARQUEZ',N'FABIOLA GUERRERO GUIDO',N'ANDREA TORRES DE LEON'),
      (N'[G] DATA ENGINEERING',N'(G3) DATA HUB - EXTENDED',N'(G3-2) DATA HUB - CLIENT SOLUTIONS',N'KAREN LOYA MARTÍN',N'JOSÉ EDUARDO ESTEBAN ROQUE',N'FABIOLA GUERRERO GUIDO',N'ANDREA TORRES DE LEON'),
      (N'[G] DATA ENGINEERING',N'(G3) DATA HUB - EXTENDED',N'(G3-3) DATA HUB - DATA BANKING',N'KAREN LOYA MARTÍN',N'KATIA IVONNE PEREA PARRA',N'FABIOLA GUERRERO GUIDO',N'ANDREA TORRES DE LEON'),
      (N'[G] DATA ENGINEERING',N'(G3) DATA HUB - EXTENDED',N'(G3-4) DATA HUB - ENTERPRISE',N'KAREN LOYA MARTÍN',N'CARLOS MIGUEL SIERRA GARDUÑO',N'FABIOLA GUERRERO GUIDO',N'ANDREA TORRES DE LEON'),
      (N'[G] DATA ENGINEERING',N'(G3) DATA HUB - EXTENDED',N'(G3-5) DATA HUB - TRANSACTIONAL S&C',N'KAREN LOYA MARTÍN',N'LINA ABREGO SANTOS',N'FABIOLA GUERRERO GUIDO',N'ANDREA TORRES DE LEON'),
      (N'[G] DATA ENGINEERING',N'(G3) DATA HUB - EXTENDED',N'(G3-7) DATA HUB - INSURANCE',N'KAREN LOYA MARTÍN',N'LUIS ANTONIO GARCÍA SEGOVIA',N'FABIOLA GUERRERO GUIDO',N'ANDREA TORRES DE LEON'),
      (N'[G] DATA ENGINEERING',N'(G6) DATA HUB LEGACY',N'(G6-3) DATA HUB INFRAESTRUCTURA',N'DANIEL ALFONSO MORENO VÁZQUEZ',N'ADRIAN NORIA',N'FABIOLA GUERRERO GUIDO',N'ANDREA TORRES DE LEON'),
      (N'AIT SOLUTIONS',N'MLE & GEN AI',N'MLE & GEN AI',N'REBECA BERENICE SANCHEZ VILORIA',N'JOSE MIGUEL JIMENEZ ULLOA',N'LAURA FUERTE PERALTA',N'LAURA FUERTE PERALTA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K1) RETAIL SYSTEMS',N'(K1-3) WEALTH MANAGEMENT',N'CECILIA MARTÍNEZ DÁVILA',N'MARCHELLO HARFUCH HERNÁNDEZ',N'TBD',N'ANA MARIA EUGENIA ARIAS TAPIA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K1) RETAIL SYSTEMS',N'(K1-5) RETAIL WEB',N'CECILIA MARTÍNEZ DÁVILA',N'JOSE MANUEL ZULAICA RUGARCIA',N'TBD',N'ANA MARIA EUGENIA ARIAS TAPIA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K1) RETAIL SYSTEMS',N'(K1-6) RETAIL MOBILE',N'CECILIA MARTÍNEZ DÁVILA',N'FRANCISCO ENRIQUE GALICIA PARADA',N'TBD',N'ANA MARIA EUGENIA ARIAS TAPIA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K1) RETAIL SYSTEMS',N'(K1-7) BRANCHES',N'CECILIA MARTÍNEZ DÁVILA',N'HUMBERTO YAHVEH CUREÑO MARTÍNEZ',N'TBD',N'ANA MARIA EUGENIA ARIAS TAPIA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K1) RETAIL SYSTEMS',N'(K1-8) OPEN MARKET',N'CECILIA MARTÍNEZ DÁVILA',N'MARÍA DOLORES CASTRO LARA',N'TBD',N'ANA MARIA EUGENIA ARIAS TAPIA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K1) RETAIL SYSTEMS',N'(K1-10) RETAIL MULTICHANNEL',N'CECILIA MARTÍNEZ DÁVILA',N'JOSE DANIEL MONTES PERALTA',N'TBD',N'ANA MARIA EUGENIA ARIAS TAPIA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K2) ENTERPRISE SYSTEMS',N'(K2-5) CONSUMER FINANCE',N'YUDITH GÓMEZ RUBIO',N'LUIS URIEL GUERRERO GARCÍA',N'TBD (CECILIA LÓPEZ HERNÁNDEZ / O RAÚL MÉNDEZ RAMIREZ)',N'CECILIA LÓPEZ HERNÁNDEZ'),
      (N'[K] SYSTEMS ENGINEERING',N'(K2) ENTERPRISE SYSTEMS',N'(K2-6) ENTERPRISE WEB',N'YUDITH GÓMEZ RUBIO',N'KARINA BAHENA GÓMEZ',N'TBD (CECILIA LÓPEZ HERNÁNDEZ / O RAÚL MÉNDEZ RAMIREZ)',N'CECILIA LÓPEZ HERNÁNDEZ'),
      (N'[K] SYSTEMS ENGINEERING',N'(K2) ENTERPRISE SYSTEMS',N'(K2-7) DIGITAL WORKPLACE',N'YUDITH GÓMEZ RUBIO',N'DAVID TELLEZ ALEGRIA',N'TBD (CECILIA LÓPEZ HERNÁNDEZ / O RAÚL MÉNDEZ RAMIREZ)',N'CECILIA LÓPEZ HERNÁNDEZ'),
      (N'[K] SYSTEMS ENGINEERING',N'(K2) ENTERPRISE SYSTEMS',N'(K2-8) SPECIALIZED PRODUCTS',N'YUDITH GÓMEZ RUBIO',N'VICTOR HUGO COUOH HERNÁNDEZ',N'TBD (CECILIA LÓPEZ HERNÁNDEZ / O RAÚL MÉNDEZ RAMIREZ)',N'CECILIA LÓPEZ HERNÁNDEZ'),
      (N'[K] SYSTEMS ENGINEERING',N'(K2) ENTERPRISE SYSTEMS',N'(K2-9) MOBILE ENTERPRISE',N'YUDITH GÓMEZ RUBIO',N'JUAN VICENTE GUERRERO BARRERA',N'TBD (CECILIA LÓPEZ HERNÁNDEZ / O RAÚL MÉNDEZ RAMIREZ)',N'CECILIA LÓPEZ HERNÁNDEZ'),
      (N'[K] SYSTEMS ENGINEERING',N'(K2) ENTERPRISE SYSTEMS',N'(K2-10) DIGITAL SMES',N'YUDITH GÓMEZ RUBIO',N'RUBÍ CONTRERAS BALLESTEROS',N'TBD (CECILIA LÓPEZ HERNÁNDEZ / O RAÚL MÉNDEZ RAMIREZ)',N'CECILIA LÓPEZ HERNÁNDEZ'),
      (N'[K] SYSTEMS ENGINEERING',N'(K2) ENTERPRISE SYSTEMS',N'(K2-11) API CHANNEL',N'YUDITH GÓMEZ RUBIO',N'CUAHTEMOC RODRÍGUEZ BRAVO',N'TBD (CECILIA LÓPEZ HERNÁNDEZ / O RAÚL MÉNDEZ RAMIREZ)',N'CECILIA LÓPEZ HERNÁNDEZ'),
      (N'[K] SYSTEMS ENGINEERING',N'(K3) INSURANCE SYSTEMS',N'(K3-5) CHANNELS',N'ISAÍ GÓMEZ FLORES',N'CESAR EDUARDO FLORES BARRETO',N'BÁRBARA VELASQUILLO NAVA',N'SALVADOR GONZÁLEZ MARTÍNEZ'),
      (N'[K] SYSTEMS ENGINEERING',N'(K3) INSURANCE SYSTEMS',N'(K3-7) CORE CROSS',N'ISAÍ GÓMEZ FLORES',N'OSVALDO MIGUEL CHAVEZ ANGELES',N'BÁRBARA VELASQUILLO NAVA',N'SALVADOR GONZÁLEZ MARTÍNEZ'),
      (N'[K] SYSTEMS ENGINEERING',N'(K3) INSURANCE SYSTEMS',N'(K3-8) INFORMATIONAL',N'ISAÍ GÓMEZ FLORES',N'VERÓNICA GUADALPUE FAJARDO PRECIADO',N'BÁRBARA VELASQUILLO NAVA',N'SALVADOR GONZÁLEZ MARTÍNEZ'),
      (N'[K] SYSTEMS ENGINEERING',N'(K4) C&IB SYSTEMS',N'(K4-4) FRONT OFFICE PLATFORM',N'DIEGO ESPINOSA HERNÁNDEZ',N'LUIS EFRÉN BOLLAIN Y GOYTIA MEZA',N'TERESA NATALIA AMMLER CASTELLANOS',N'ALEJANDRO FERREYRA MOTA / TERESA NATALIA AMMLER CASTELLANOS'),
      (N'[K] SYSTEMS ENGINEERING',N'(K4) C&IB SYSTEMS',N'(K4-5) EQUITY',N'DIEGO ESPINOSA HERNÁNDEZ',N'MARIA DEL REFUGIO RODRIGUEZ GONZALEZ',N'TERESA NATALIA AMMLER CASTELLANOS',N'ALEJANDRO FERREYRA MOTA / TERESA NATALIA AMMLER CASTELLANOS'),
      (N'[K] SYSTEMS ENGINEERING',N'(K4) C&IB SYSTEMS',N'(K4-6) IB&F / GTB',N'DIEGO ESPINOSA HERNÁNDEZ',N'CLARISA BEATRIZ HERNANDEZ CARPIO',N'TERESA NATALIA AMMLER CASTELLANOS',N'ALEJANDRO FERREYRA MOTA / TERESA NATALIA AMMLER CASTELLANOS'),
      (N'[K] SYSTEMS ENGINEERING',N'(K4) C&IB SYSTEMS',N'(K4-7) FX & DERIVATIVES',N'DIEGO ESPINOSA HERNÁNDEZ',N'ERICK SAID FRANKLIN ZAMORA',N'TERESA NATALIA AMMLER CASTELLANOS',N'ALEJANDRO FERREYRA MOTA / TERESA NATALIA AMMLER CASTELLANOS'),
      (N'[K] SYSTEMS ENGINEERING',N'(K4) C&IB SYSTEMS',N'(K4-8) FIXED INCOME & RATES',N'DIEGO ESPINOSA HERNÁNDEZ',N'WENDY VERONICA MARTINEZ GUZMAN',N'TERESA NATALIA AMMLER CASTELLANOS',N'ALEJANDRO FERREYRA MOTA / TERESA NATALIA AMMLER CASTELLANOS'),
      (N'[K] SYSTEMS ENGINEERING',N'(K4) C&IB SYSTEMS',N'(K4-9) ASSET MANAGEMENT',N'DIEGO ESPINOSA HERNÁNDEZ',N'CARLOS MANUEL HERAS TOLEDANO',N'TERESA NATALIA AMMLER CASTELLANOS',N'ALEJANDRO FERREYRA MOTA / TERESA NATALIA AMMLER CASTELLANOS'),
      (N'[K] SYSTEMS ENGINEERING',N'(K4) C&IB SYSTEMS',N'(K4-10) PRIVATE BANKING',N'DIEGO ESPINOSA HERNÁNDEZ',N'MARCHELLO HARFUCH HERNANDEZ',N'TERESA NATALIA AMMLER CASTELLANOS',N'ALEJANDRO FERREYRA MOTA / TERESA NATALIA AMMLER CASTELLANOS'),
      (N'[K] SYSTEMS ENGINEERING',N'(K4) C&IB SYSTEMS',N'(K4-11) CROSS FUNCTIONS',N'DIEGO ESPINOSA HERNÁNDEZ',N'ANTONIO MONTES NUÑEZ',N'TERESA NATALIA AMMLER CASTELLANOS',N'ALEJANDRO FERREYRA MOTA / TERESA NATALIA AMMLER CASTELLANOS'),
      (N'[K] SYSTEMS ENGINEERING',N'(K4) C&IB SYSTEMS',N'(K4-12) RISK PLATFORMS',N'DIEGO ESPINOSA HERNÁNDEZ',N'SANTIAGO ALAN PACHECO RAMOS',N'TERESA NATALIA AMMLER CASTELLANOS',N'ALEJANDRO FERREYRA MOTA / TERESA NATALIA AMMLER CASTELLANOS'),
      (N'[K] SYSTEMS ENGINEERING',N'(K5) CORPORATE FUNCTIONS SYSTEMS',N'(K5-5) TALENT & CULTURE',N'CARLOS MANUEL PÉREZ RUBIO',N'JOSE SANTOS MORA DUARTE',N'EDGAR CARREOLA MORALES',N'EDGAR CARREOLA MORALES'),
      (N'[K] SYSTEMS ENGINEERING',N'(K5) CORPORATE FUNCTIONS SYSTEMS',N'(K5-6) COMPLIANCE & LEGAL',N'CARLOS MANUEL PÉREZ RUBIO',N'GUADALUPE ELIZETH FAJARDO MARTINEZ',N'EDGAR CARREOLA MORALES',N'EDGAR CARREOLA MORALES'),
      (N'[K] SYSTEMS ENGINEERING',N'(K5) CORPORATE FUNCTIONS SYSTEMS',N'(K5-7) RETAIL RISK',N'CARLOS MANUEL PÉREZ RUBIO',N'JOSE LENIN RUIZ VAZQUEZ',N'EDGAR CARREOLA MORALES',N'EDGAR CARREOLA MORALES'),
      (N'[K] SYSTEMS ENGINEERING',N'(K5) CORPORATE FUNCTIONS SYSTEMS',N'(K5-8) AACCS & GABINETE',N'CARLOS MANUEL PÉREZ RUBIO',N'HECTOR HORACIO SANCHEZ ITURBE',N'EDGAR CARREOLA MORALES',N'EDGAR CARREOLA MORALES'),
      (N'[K] SYSTEMS ENGINEERING',N'(K5) CORPORATE FUNCTIONS SYSTEMS',N'(K5-9) FINANCE',N'CARLOS MANUEL PÉREZ RUBIO',N'HAMLET MADRID GOMEZ',N'EDGAR CARREOLA MORALES',N'EDGAR CARREOLA MORALES'),
      (N'[K] SYSTEMS ENGINEERING',N'(K5) CORPORATE FUNCTIONS SYSTEMS',N'(K5-10) LOCAL SERVICES',N'CARLOS MANUEL PÉREZ RUBIO',N'YAZMIN SALAS GUZMAN',N'EDGAR CARREOLA MORALES',N'EDGAR CARREOLA MORALES'),
      (N'[K] SYSTEMS ENGINEERING',N'(K5) CORPORATE FUNCTIONS SYSTEMS',N'(K5-11) CREDIT ACQUISITION',N'CARLOS MANUEL PÉREZ RUBIO',N'VICTORIA DEL CARMEN HERNANDEZ RETANA',N'EDGAR CARREOLA MORALES',N'EDGAR CARREOLA MORALES'),
      (N'[K] SYSTEMS ENGINEERING',N'(K6) CORE BANKING PRODUCTS',N'(K6-5) ACCOUNTS',N'ENRIQUE HERRERA GIL',N'OSVALDO MARTINEZ BUCIO',N'GUSTAVO ROGELIO LOPEZ PEREZ',N'CARLOS HERNANDEZ MENDIETA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K6) CORE BANKING PRODUCTS',N'(K6-6) PAYROLLS AND TRANSFERS',N'ENRIQUE HERRERA GIL',N'HECTOR GONZALO RAMIREZ MEMIJE',N'GUSTAVO ROGELIO LOPEZ PEREZ',N'CARLOS HERNANDEZ MENDIETA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K6) CORE BANKING PRODUCTS',N'(K6-7) LOANS / LENDING',N'ENRIQUE HERRERA GIL',N'CESAR JAVIER JUAREZ GUTIERREZ',N'GUSTAVO ROGELIO LOPEZ PEREZ',N'CARLOS HERNANDEZ MENDIETA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K6) CORE BANKING PRODUCTS',N'(K6-9) CONTRACTING AND AUTHENTICATION MODULES',N'ENRIQUE HERRERA GIL',N'HECTOR GONZALO RAMIREZ MEMIJE',N'GUSTAVO ROGELIO LOPEZ PEREZ',N'CARLOS HERNANDEZ MENDIETA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K6) CORE BANKING PRODUCTS',N'(K6-10) CLIENT INFRASTRUCTURE',N'ENRIQUE HERRERA GIL',N'VERONICA SANCHEZ DAVILA',N'GUSTAVO ROGELIO LOPEZ PEREZ',N'CARLOS HERNANDEZ MENDIETA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K6) CORE BANKING PRODUCTS',N'(K6-11) CUSTOMER OPERATIONAL DATA LAYER',N'ENRIQUE HERRERA GIL',N'RUBI CONTRERAS BALLESTEROS',N'GUSTAVO ROGELIO LOPEZ PEREZ',N'CARLOS HERNANDEZ MENDIETA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K7) CORE CROSS SYSTEMS',N'(K7-5) ATMS',N'ROSA ISELA BRIONES HERNÁNDEZ',N'MARCO ANTONIO GUTIÉRREZ MARQUEZ',N'JANETT MARIBEL VERA GUZMÁN',N'DIEGO GÁLVEZ CADENA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K7) CORE CROSS SYSTEMS',N'(K7-6) CC LÍNEA BBVA',N'ROSA ISELA BRIONES HERNÁNDEZ',N'JORGE PEDRAZA RAMIREZ',N'JANETT MARIBEL VERA GUZMÁN',N'DIEGO GÁLVEZ CADENA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K7) CORE CROSS SYSTEMS',N'(K7-8) ACCOUNT STATEMENTS',N'ROSA ISELA BRIONES HERNÁNDEZ',N'BLANCA LILIA CAMARENA REYES',N'JANETT MARIBEL VERA GUZMÁN',N'DIEGO GÁLVEZ CADENA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K7) CORE CROSS SYSTEMS',N'(K7-10) APPLICATION SECURITY',N'ROSA ISELA BRIONES HERNÁNDEZ',N'FRANCISCO EDUARDO HERNANDEZ PORTILLO',N'JANETT MARIBEL VERA GUZMÁN',N'DIEGO GÁLVEZ CADENA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K7) CORE CROSS SYSTEMS',N'(K7-11) DIGITAL CONTACTABILITY',N'ROSA ISELA BRIONES HERNÁNDEZ',N'EDITH GUERRERO HUERTA',N'JANETT MARIBEL VERA GUZMÁN',N'DIEGO GÁLVEZ CADENA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K7) CORE CROSS SYSTEMS',N'(K7-12) CC MULTIASISTENCIA & CC COBRANZAS',N'ROSA ISELA BRIONES HERNÁNDEZ',N'DIANA SANCHEZ SANCHEZ',N'JANETT MARIBEL VERA GUZMÁN',N'DIEGO GÁLVEZ CADENA'),
      (N'[K] SYSTEMS ENGINEERING',N'(K8) PAYMENTS SYSTEMS',N'(K8-5) BANXICO / SPEI / SPID / CODI',N'JEREMY ALAIN BERRAS',N'PAOLA MEDINA SANCHEZ',N'MARTHA CAROLINA GUZMAN CHAVEZ',N'YOLANDA IVONE CAMACHO VARGAS'),
      (N'[K] SYSTEMS ENGINEERING',N'(K8) PAYMENTS SYSTEMS',N'(K8-8) CREDITS',N'JEREMY ALAIN BERRAS',N'BENJAMIN TRUJILLO BELTRAN',N'MARTHA CAROLINA GUZMAN CHAVEZ',N'YOLANDA IVONE CAMACHO VARGAS'),
      (N'[K] SYSTEMS ENGINEERING',N'(K8) PAYMENTS SYSTEMS',N'(K8-9) MERCHANTS',N'JEREMY ALAIN BERRAS',N'BENJAMÍN TRUJILLO BELTRÁN',N'MARTHA CAROLINA GUZMAN CHAVEZ',N'YOLANDA IVONE CAMACHO VARGAS'),
      (N'[K] SYSTEMS ENGINEERING',N'(K8) PAYMENTS SYSTEMS',N'(K8-10) METHODS',N'JEREMY ALAIN BERRAS',N'CINTYA BARRERA GONZÁLEZ',N'MARTHA CAROLINA GUZMAN CHAVEZ',N'YOLANDA IVONE CAMACHO VARGAS'),
      (N'[K] SYSTEMS ENGINEERING',N'(K8) PAYMENTS SYSTEMS',N'(K8-11) AUTORIZADOR',N'JEREMY ALAIN BERRAS',N'ULISES JOAQUÍN ESPINOSA DORANTES',N'MARTHA CAROLINA GUZMAN CHAVEZ',N'YOLANDA IVONE CAMACHO VARGAS'),
      (N'[K] SYSTEMS ENGINEERING',N'(K8) PAYMENTS SYSTEMS',N'(K8-12) SUBSCRIPTIONS & SERVICES',N'JEREMY ALAIN BERRAS',N'ROGELIO MENDOZA SANTOS',N'MARTHA CAROLINA GUZMAN CHAVEZ',N'YOLANDA IVONE CAMACHO VARGAS'),
      (N'[K] SYSTEMS ENGINEERING',N'(K9) SYSTEMS STRATEGY & TRANSFORMATION',N'(K9-2) AUTOMATION',N'MARIANA RABADÁN RODRÍGUEZ',N'NANCY GRAJALES DIAZ',N'PABLO SAÚL RAMÍREZ RAMÍREZ (INTERINO)',N'PABLO SAÚL RAMÍREZ RAMÍREZ'),
      (N'[K] SYSTEMS ENGINEERING',N'(K12) RELATIONSHIP MODELS & CET SYSTEMS',N'(K12-3) CRM LEGACY',N'MARÍA NORMA MÉNDEZ LÓPEZ',N'MARÍA ANGÉLICA ALEJANDRA LEDEZMA CORONA',N'ANA LUISA FLORES HERNÁNDEZ',N'ANA LUISA FLORES HERNÁNDEZ'),
      (N'[K] SYSTEMS ENGINEERING',N'(K12) RELATIONSHIP MODELS & CET SYSTEMS',N'(K12-4) SALESFORCE',N'MARÍA NORMA MÉNDEZ LÓPEZ',N'TBD',N'ANA LUISA FLORES HERNÁNDEZ',N'ANA LUISA FLORES HERNÁNDEZ'),
      (N'[K] SYSTEMS ENGINEERING',N'(K12) RELATIONSHIP MODELS & CET SYSTEMS',N'(K12-5) SMART ASSISTANTS (BLUE)',N'MARÍA NORMA MÉNDEZ LÓPEZ',N'JAZMIN BERENICE RAMOS BENÍTEZ',N'ANA LUISA FLORES HERNÁNDEZ',N'ANA LUISA FLORES HERNÁNDEZ'),
      (N'[K] SYSTEMS ENGINEERING',N'(K12) RELATIONSHIP MODELS & CET SYSTEMS',N'(K12-6) CLIENT DATA PERFORMANCE',N'MARÍA NORMA MÉNDEZ LÓPEZ',N'TBD',N'ANA LUISA FLORES HERNÁNDEZ',N'ANA LUISA FLORES HERNÁNDEZ'),
      (N'[K] SYSTEMS ENGINEERING',N'(K12) RELATIONSHIP MODELS & CET SYSTEMS',N'(K12-7) ODL & CET PROGRAM',N'MARÍA NORMA MÉNDEZ LÓPEZ',N'FIDEL MARTÍNEZ GUTIÉRREZ',N'ANA LUISA FLORES HERNÁNDEZ',N'ANA LUISA FLORES HERNÁNDEZ');

  MERGE bbva.EngineeringSpecialtyCatalog AS target
  USING @Seed AS source ON target.N3=source.N3 AND target.Guild=source.Guild AND target.Specialty=source.Specialty
  WHEN MATCHED THEN UPDATE SET GuildLeader=source.GuildLeader,SpecialtyOwner=source.SpecialtyOwner,PortfolioStaffing=source.PortfolioStaffing,Staffer=source.Staffer,UpdatedAt=SYSUTCDATETIME(),UpdatedByEmail=N'system.v26@basebfs.local'
  WHEN NOT MATCHED THEN INSERT(N3,Guild,Specialty,GuildLeader,SpecialtyOwner,PortfolioStaffing,Staffer,Status,CreatedByEmail,UpdatedByEmail)
    VALUES(source.N3,source.Guild,source.Specialty,source.GuildLeader,source.SpecialtyOwner,source.PortfolioStaffing,source.Staffer,N'ACTIVE',N'system.v26@basebfs.local',N'system.v26@basebfs.local');
  IF OBJECT_ID(N'bbva.SecondTechnologyCertificationPlan',N'U') IS NULL
  BEGIN
    CREATE TABLE bbva.SecondTechnologyCertificationPlan(
      Id UNIQUEIDENTIFIER NOT NULL CONSTRAINT PK_BBVA_SecondTechnologyCertificationPlan PRIMARY KEY DEFAULT NEWID(),
      PersonId UNIQUEIDENTIFIER NOT NULL,CertificationId UNIQUEIDENTIFIER NOT NULL,
      Status NVARCHAR(24) NOT NULL CONSTRAINT DF_BBVA_SecondCertificationPlan_Status DEFAULT N'PLANNED',TargetDate DATE NULL,Notes NVARCHAR(1000) NULL,
      CreatedAt DATETIME2(7) NOT NULL CONSTRAINT DF_BBVA_SecondCertificationPlan_CreatedAt DEFAULT SYSUTCDATETIME(),UpdatedAt DATETIME2(7) NOT NULL CONSTRAINT DF_BBVA_SecondCertificationPlan_UpdatedAt DEFAULT SYSUTCDATETIME(),
      CreatedByEmail NVARCHAR(320) NOT NULL,UpdatedByEmail NVARCHAR(320) NOT NULL,
      CONSTRAINT FK_BBVA_SecondCertificationPlan_Person FOREIGN KEY(PersonId) REFERENCES bbva.Person(Id),
      CONSTRAINT FK_BBVA_SecondCertificationPlan_Cert FOREIGN KEY(CertificationId) REFERENCES bbva.CertificationCatalog(Id),
      CONSTRAINT CK_BBVA_SecondCertificationPlan_Status CHECK(Status IN(N'PLANNED',N'IN_PROGRESS',N'COMPLETED',N'CANCELLED',N'DELETED'))
    );
    CREATE UNIQUE INDEX UX_BBVA_SecondCertificationPlan_PersonCertification ON bbva.SecondTechnologyCertificationPlan(PersonId,CertificationId);
    CREATE INDEX IX_BBVA_SecondCertificationPlan_Status ON bbva.SecondTechnologyCertificationPlan(Status,UpdatedAt DESC);
  END;
  IF OBJECT_ID(N'bbva.PersonCertificationAttempt',N'U') IS NOT NULL
  BEGIN
    IF COL_LENGTH(N'bbva.PersonCertificationAttempt',N'UpdatedAt') IS NULL ALTER TABLE bbva.PersonCertificationAttempt ADD UpdatedAt DATETIME2(7) NULL;
    IF COL_LENGTH(N'bbva.PersonCertificationAttempt',N'UpdatedByEmail') IS NULL ALTER TABLE bbva.PersonCertificationAttempt ADD UpdatedByEmail NVARCHAR(320) NULL;
  END;
  COMMIT TRANSACTION;
END TRY
BEGIN CATCH
  IF @@TRANCOUNT>0 ROLLBACK TRANSACTION;
  THROW;
END CATCH;
