import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'..','..');
const read=(relative)=>fs.readFileSync(path.join(root,relative),'utf8');
const migration=read('api/scripts/migrate-bbva-certification-coverage-groups-v31.20.sql');
const repository=read('api/src/lib/bbvaCollaboratorCertificationRepository.ts');
const service=read('api/src/lib/bbvaCollaboratorCertificationService.ts');
const dialog=read('src/componentsBBVATalent/CertificationCoverageDialog.tsx');
const page=read('src/pagesBBVATalent/collaboratorCertifications/CollaboratorCertificationsPage.tsx');
const tracking=read('src/pagesBBVATalent/certifications/CertificationTrackingPage.tsx');
assert.match(migration,/BETWEEN 1 AND 255/);
assert.match(migration,/CertificationType<>N'TECHNOLOGICAL'/);
assert.match(repository,/Solo las certificaciones tecnológicas pueden formar grupos de cobertura/);
assert.match(repository,/index \+ 1/);
assert.match(service,/memberRecordIds/);
assert.match(dialog,/role="dialog"/);
assert.match(dialog,/Orden de relevo/);
assert.match(dialog,/dos o más certificaciones tecnológicas/);
assert.match(dialog,/Desarrollo Seguro, Normativa/);
assert.match(page,/Configurar cobertura tecnológica/);
assert.doesNotMatch(page,/Primaria|Secundaria|Terciaria/);
assert.doesNotMatch(tracking,/Primaria|Secundaria|Terciaria/);
assert.match(tracking,/Cobertura tecnológica/);
console.log('BBVA Certification Coverage Groups V31.20: OK');
console.log('- configuración se realiza en modal: OK');
console.log('- solo certificaciones TECHNOLOGICAL son elegibles: OK');
console.log('- grupos soportan más de tres certificaciones mediante orden 1..255: OK');
console.log('- UI elimina primaria/secundaria/terciaria: OK');
