import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const here=path.dirname(fileURLToPath(import.meta.url));
const root=path.resolve(here,'..','..');
const read=(relative)=>fs.readFileSync(path.join(root,relative),'utf8');
const helper=read('api/src/lib/bbvaCertificationCoverage.ts');
const repository=read('api/src/lib/bbvaCollaboratorCertificationRepository.ts');
const tracking=read('src/pagesBBVATalent/certifications/CertificationTrackingPage.tsx');
const collaborator=read('src/pagesBBVATalent/collaboratorCertifications/CollaboratorCertificationsPage.tsx');
const types=read('src/pagesBBVATalent/types/collaboratorCertification.ts');
assert.match(helper,/handover/);
assert.match(helper,/previousCertificationName/);
assert.match(helper,/noValidCoverage/);
assert.match(helper,/item\.baseStatus === 'APPROVED'/);
assert.match(repository,/coverageHandover/);
assert.match(repository,/coverageNoValidCertification/);
assert.match(types,/coveragePreviousCertificationName/);
assert.match(tracking,/Sin cobertura tecnológica vigente/);
assert.match(tracking,/Relevos de cobertura tecnológica|Seguimiento de cobertura tecnológica/);
assert.match(tracking,/Alterna por vencer/);
assert.match(collaborator,/Sin cobertura tecnológica vigente/);
assert.match(collaborator,/Relevo activo/);
assert.match(collaborator,/Alterna por vencer/);
console.log('BBVA Certification Coverage Alerts V31.21: OK');
console.log('- relevo se expone explicitamente y conserva certificacion anterior: OK');
console.log('- grupo sin ninguna certificacion vigente genera alerta critica: OK');
console.log('- alternas proximas a vencer siguen visibles sin inflar metricas: OK');
console.log('- no requiere nueva migracion SQL: OK');
