import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const read=(relative)=>fs.readFileSync(path.join(root,relative),'utf8');
const app=read('src/App.tsx');
const layout=read('src/componentsBBVATalent/BBVALayout.tsx');
const context=read('src/componentsBBVATalent/BBVAContextBar.tsx');
const sidebar=read('src/componentsBBVATalent/BBVASidebar.tsx');
const card=read('src/componentsBBVATalent/BBVACard.tsx');
const metric=read('src/componentsBBVATalent/BBVAMetricCard.tsx');
const multi=read('src/componentsBBVATalent/BBVAMultiSelect.tsx');
const structure=read('src/componentsBBVATalent/BBVAStructureFilter.tsx');
const schedule=read('src/componentsBBVATalent/CertificationScheduleDialog.tsx');
const communication=read('src/componentsBBVATalent/CertificationCommunicationDialog.tsx');
const pagination=read('src/componentsBBVATalent/BBVAPagination.tsx');
const css=read('src/index.css');
const agents=read('AGENTS.md');
assert.match(app,/<BBVALayout themeMode=\{themeMode\}>/);
assert.match(layout,/bbva-workspace/);
assert.match(layout,/bbva-main-surface/);
assert.match(context,/bg-\[#020617\]/);
assert.match(sidebar,/bg-\[#020617\]/);
assert.doesNotMatch(sidebar,/bg-\[#081426\]/);
assert.match(card,/bg-\[#111c2e\]\/95/);
assert.match(metric,/bg-blue-400\/15/);
assert.match(metric,/bg-violet-400\/15/);
assert.match(multi,/bg-\[#0b1728\]/);
assert.match(multi,/text-cyan-100/);
assert.match(structure,/bg-\[#0b1728\]/);
assert.match(structure,/text-cyan-100/);
assert.match(schedule,/bg-\[#0b1728\]/);
assert.match(communication,/bg-\[#0b1728\]/);
assert.match(pagination,/px-3 py-1\.5/);
assert.match(css,/\.bbva-workspace table tbody td/);
assert.match(css,/\.bbva-dark \.bbva-main-surface/);
assert.match(css,/--bbva-dark-main: #020617/);
assert.match(css,/\.bbva-workspace\.bbva-dark \.bbva-table-shell/);
assert.match(css,/\.bbva-table-shell tbody,[\s\S]*\.bbva-table-shell tr,[\s\S]*\.bbva-table-shell td,[\s\S]*background-color: #020617 !important/);
assert.match(css,/\.bbva-table-shell th,[\s\S]*\.bbva-table-shell td,[\s\S]*background-color: #020617 !important/);
assert.match(css,/text-violet-700/);
assert.match(css,/text-orange-700/);
assert.match(css,/V31\.15a — POLISH OSCURO BBVA/);
assert.match(agents,/V31\.15a — polish visual Dark BBVA/);
console.log('BBVA Dark Polish V31.15a: OK');
console.log('- Light/Dark enlaza BBVALayout al estado global sin clase stale: OK');
console.log('- header/contexto, nav y main BBVA usan #020617: OK');
console.log('- contraste y semántica de color reforzados: OK');
console.log('- selects/portales/dialogs cubiertos en dark: OK');
console.log('- tablas Dark: wrapper, header, filas y celdas #020617: OK');
console.log('- densidad vertical de tablas/paginación reducida: OK');
