import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const read=(relative)=>fs.readFileSync(path.join(root,relative),'utf8');
const vendor=read('api/src/lib/bbvaVendorCalendar.ts');
const repo=read('api/src/lib/bbvaOperationalQuarterRepository.ts');
const service=read('api/src/lib/bbvaOperationalQuarterService.ts');
const fn=read('api/src/functions/bbvaOperationalQuarters.ts');
const api=read('src/pagesBBVATalent/api/operationalQuarterApi.ts');
const page=read('src/pagesBBVATalent/catalogs/OperationalQuarterCatalogPage.tsx');
const talent=read('src/pagesBBVATalent/talentBank/TalentBankPage.tsx');
assert.doesNotMatch(vendor,/sourceStart<=previousEnd/);
assert.match(vendor,/operationalStartDate=validIso/);
assert.match(service,/updateConfiguration/);
assert.match(service,/async deletePeriod/);
assert.match(service,/async deleteYear/);
assert.match(repo,/async deletePeriod/);
assert.match(fn,/service\.deletePeriod/);
assert.match(fn,/service\.deleteYear/);
assert.match(api,/removeYear/);
assert.match(page,/Ventana Vendors · editable/);
assert.match(page,/Ventana operativa · editable/);
assert.match(page,/pueden traslaparse/);
assert.match(page,/Sugerida por Vendors/);
assert.match(page,/ConfirmDialog/);
assert.match(page,/Eliminar año/);
assert.match(talent,/label="Nombre"/);
assert.doesNotMatch(talent,/label="Persona"/);
assert.doesNotMatch(talent,/bg-amber-50\/35 ring-1 ring-inset ring-amber-200/);
assert.match(talent,/Urgente · \+60 días/);
console.log('Quarter Overlap + Talent UX V31.14: OK');
console.log('- traslape Vendors permitido con ventana operativa independiente: OK');
console.log('- eliminación segura V31.13 preservada: OK');
console.log('- Banco de talento usa columna Nombre: OK');
console.log('- permanencia urgente conserva badge sin remarcar toda la fila: OK');
