import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const read=(relative)=>fs.readFileSync(path.join(root,relative),'utf8');
const vendor=read('api/src/lib/bbvaVendorCalendar.ts');
const repo=read('api/src/lib/bbvaOperationalQuarterRepository.ts');
const fn=read('api/src/functions/bbvaOperationalQuarters.ts');
const page=read('src/pagesBBVATalent/catalogs/OperationalQuarterCatalogPage.tsx');
const api=read('src/pagesBBVATalent/api/operationalQuarterApi.ts');
const tracking=read('src/pagesBBVATalent/certifications/CertificationTrackingPage.tsx');
const metrics=read('src/pagesBBVATalent/certifications/CertificationMetricsPage.tsx');
const periods=read('src/pagesBBVATalent/lib/periodOptions.ts');
const sql=read('api/scripts/migrate-bbva-operational-quarter-v31.9.sql');
assert.match(vendor,/generatedVendorYear/);
assert.match(vendor,/sourceConfigured/);
assert.match(vendor,/configuredVendorQuarters/);
assert.match(repo,/SourceStartDate/);
assert.match(repo,/createYear/);
assert.match(fn,/methods: \['GET','POST'\]/);
assert.match(fn,/agrega primero el año/);
assert.match(page,/Agregar año/);
assert.match(page,/Vendors por confirmar/);
assert.match(api,/createYear/);
assert.match(sql,/SourceConfigured/);
assert.doesNotMatch(periods,/filter\(\(item\)=>item\.year===year\)/);
assert.match(periods,/currentYear/);
assert.doesNotMatch(tracking,/Persona o certificación/);
assert.match(tracking,/filters\.search/);
assert.match(tracking,/Todos los intentos/);
assert.match(tracking,/Límite de intentos agotado/);
assert.match(tracking,/Vencen en \$\{formatPeriodCode\(effectiveQuarterCode\)\}/);
const techIndex=tracking.indexOf('ariaLabel="Tecnología o certificación"');
const statusIndex=tracking.indexOf('ariaLabel="Estado"');
assert.ok(techIndex>=0&&statusIndex>techIndex,'Estado debe ser el último filtro de Seguimiento.');
assert.match(metrics,/data\?\.filters\.certifications/);
assert.match(metrics,/Todas las certificaciones/);
const certIndex=metrics.indexOf('ariaLabel="Certificación"');
const metricsStatusIndex=metrics.indexOf('ariaLabel="Estado de certificación"');
assert.ok(certIndex>=0&&metricsStatusIndex>certIndex,'Estado debe quedar al final en Métricas.');
console.log('Periodos multiaño + filtros BBVA V31.9: OK');
console.log('- Agregar año con 4 periodos y Vendors configurable: OK');
console.log('- selectores de periodo muestran años configurados: OK');
console.log('- Seguimiento conserva filtros estructurados y suma búsqueda compacta: OK');
console.log('- Vence en periodo separado de Próxima a vencer: OK');
console.log('- Métricas incluye filtro Certificación independiente de Tecnología: OK');
console.log('- Estado permanece como último filtro: OK');
