import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const read=(r)=>fs.readFileSync(path.join(root,r),'utf8');
const collaborators=read('src/pagesBBVATalent/collaborators/CollaboratorsPage.tsx');
const dashboard=read('src/pagesBBVATalent/dashboard/BBVADashboardPage.tsx');
const insight=read('src/componentsBBVATalent/BBVAInsightCard.tsx');
assert.match(collaborators,/min-w-\[900px\] table-auto/);
assert.doesNotMatch(collaborators,/min-w-\[1020px\] table-fixed/);
assert.match(collaborators,/w-px whitespace-nowrap[^>]*><BBVATableSortHeader label=\"DM\"/);
assert.match(collaborators,/w-px whitespace-nowrap[^>]*><BBVATableSortHeader label=\"Alta BBVA\"/);
assert.match(dashboard,/visibleRecommendations/);
assert.ok(dashboard.includes('(data?.recommendations??[])'),'Debe consumir todas las recomendaciones devueltas por backend.');
assert.doesNotMatch(dashboard,/recommendations\.slice\(0,4\)/);
assert.match(dashboard,/overflow-x-auto/);
assert.match(dashboard,/scrollBy\(\{left:direction\*step,behavior:'smooth'\}\)/);
assert.match(dashboard,/setInterval/);
assert.match(dashboard,/actionLabel=\"Poner en marcha\"/);
assert.match(dashboard,/onDismiss=/);
assert.doesNotMatch(insight,/hover:-translate-y-px/);
assert.match(insight,/dismissLabel/);
console.log('Adaptive Table + Recommendation Flow V31.6a: OK');
console.log('- tabla Colaboradores table-auto con columnas cortas compactas: OK');
console.log('- recomendaciones horizontales sin límite artificial de 4: OK');
console.log('- autoavance horizontal con pausa al interactuar: OK');
console.log('- descartar / poner en marcha: OK');
