import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const read=(relative)=>fs.readFileSync(path.join(root,relative),'utf8');
const vendor=read('api/src/lib/bbvaVendorCalendar.ts');
const dashboardService=read('api/src/lib/bbvaDashboardService.ts');
const certificationService=read('api/src/lib/bbvaCollaboratorCertificationService.ts');
const certificationRepo=read('api/src/lib/bbvaCollaboratorCertificationRepository.ts');
const tracking=read('src/pagesBBVATalent/certifications/CertificationTrackingPage.tsx');
const metrics=read('src/pagesBBVATalent/certifications/CertificationMetricsPage.tsx');
const dashboard=read('src/pagesBBVATalent/dashboard/BBVADashboardPage.tsx');
const nav=read('src/componentsBBVATalent/bbvaNavigation.ts');
const app=read('src/App.tsx');
const sql=read('api/scripts/migrate-bbva-operational-quarter-v31.8.sql');
assert.match(vendor,/defaultOperationalQuarterWindow/);
assert.match(vendor,/configuredVendorQuarters/);
assert.match(vendor,/validateOperationalQuarterConfiguration/);
assert.match(vendor,/sourceStartDate/);
assert.match(vendor,/operationalStartDate/);
assert.match(vendor,/const startDate=source\.startDate\.endsWith\('-01'\)\?source\.startDate:addMonthsFirstDay\(source\.startDate,1\)/);
assert.match(vendor,/const endDate=lastDayOfMonth\(source\.endDate\)/);
assert.match(dashboardService,/operationalQuarterRepository\.listOverrides\(\)/);
assert.match(dashboardService,/filters\.certificationStatus === 'DUE_IN_PERIOD'/);
assert.doesNotMatch(dashboardService,/certificationStatus\(cert, todayIso, selectedQuarter\)/);
assert.match(certificationService,/vendorQuarterForDate\(item\.expirationDate, operationalQuarterOverrides\)/);
assert.match(certificationService,/vendorQuarterContext\(new Date\(\), null, operationalQuarterOverrides\)/);
assert.doesNotMatch(certificationRepo,/return rows\.filter\(\(row\) => row\.status !== 'VALID'/);
assert.match(tracking,/matchesTrackingStatusFilter/);
assert.match(tracking,/DUE_IN_PERIOD/);
assert.match(tracking,/Próximas a vencer/);
assert.doesNotMatch(tracking,/const attentionRequired=/);
assert.match(metrics,/DUE_IN_PERIOD/);
assert.match(metrics,/Próximas a vencer/);
assert.match(dashboard,/DUE_IN_PERIOD/);
assert.match(nav,/operational-periods/);
assert.match(app,/OperationalQuarterCatalogPage/);
assert.match(sql,/bbva\.OperationalQuarterConfig/);
assert.match(sql,/OperationalStartDate DATE NOT NULL/);
assert.match(sql,/OperationalEndDate DATE NOT NULL/);
// Regla de negocio pura: fecha real 23/09 -> inicio operativo 01/10; fin real 22/12 -> 31/12.
const operational=(start,end)=>{const startMonth=new Date(`${start.slice(0,7)}-01T00:00:00Z`);if(!start.endsWith('-01'))startMonth.setUTCMonth(startMonth.getUTCMonth()+1);const endMonth=new Date(`${end.slice(0,7)}-01T00:00:00Z`);endMonth.setUTCMonth(endMonth.getUTCMonth()+1);endMonth.setUTCDate(0);return [startMonth.toISOString().slice(0,10),endMonth.toISOString().slice(0,10)];};
assert.deepEqual(operational('2026-09-23','2026-12-22'),['2026-10-01','2026-12-31']);
assert.deepEqual(operational('2026-06-23','2026-09-22'),['2026-07-01','2026-09-30']);
console.log('Periodos Operativos BBVA V31.8: OK');
console.log('- meses completos, sin dividir el cambio de Q: OK');
console.log('- configuración persistente con fallback sugerido: OK');
console.log('- Seguimiento/Métricas/Panel consumen la misma fuente: OK');
console.log('- Próxima a vencer separado de Vence en el periodo: OK');
console.log('- Todos los estados conserva Vigentes antes de filtrar Q: OK');
