import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const read=(relative)=>fs.readFileSync(path.join(root,relative),'utf8');
const vendor=read('api/src/lib/bbvaVendorCalendar.ts');
const repo=read('api/src/lib/bbvaOperationalQuarterRepository.ts');
const service=read('api/src/lib/bbvaOperationalQuarterService.ts');
const fn=read('api/src/functions/bbvaOperationalQuarters.ts');
const catalog=read('src/pagesBBVATalent/catalogs/OperationalQuarterCatalogPage.tsx');
const api=read('src/pagesBBVATalent/api/operationalQuarterApi.ts');
const tracking=read('src/pagesBBVATalent/certifications/CertificationTrackingPage.tsx');
const dashboardService=read('api/src/lib/bbvaDashboardService.ts');
const certificationService=read('api/src/lib/bbvaCollaboratorCertificationService.ts');
const metrics=read('src/pagesBBVATalent/certifications/CertificationMetricsPage.tsx');
const sql=read('api/scripts/migrate-bbva-operational-quarter-v31.14.sql');
const legacySql=read('api/scripts/migrate-bbva-operational-quarter-v31.10.sql');
assert.match(vendor,/override\?\.operationalStartDate/);
assert.match(vendor,/override\?\.operationalEndDate/);
assert.doesNotMatch(vendor,/Las ventanas Vendors .* se traslapan/);
assert.match(vendor,/Las ventanas Vendors son referencias reales del negocio y pueden traslaparse/);
assert.match(vendor,/validateOperationalQuarterConfiguration/);
assert.match(service,/updateConfiguration\(/);
assert.match(service,/operationalStartDate,operationalEndDate/);
assert.match(service,/invalidateMetricSnapshots\(affected\)/);
assert.match(repo,/OperationalStartDate/);
assert.match(fn,/body\?\.operationalStartDate/);
assert.match(fn,/body\?\.operationalEndDate/);
assert.match(fn,/service\.updateConfiguration\(/);
assert.match(api,/OperationalQuarterDraft\s*\{\s*sourceStartDate:string;\s*sourceEndDate:string;\s*operationalStartDate:string;\s*operationalEndDate:string;\s*\}/);
assert.match(catalog,/ariaLabel=\{`Inicio operativo/);
assert.match(catalog,/ariaLabel=\{`Fin operativo/);
assert.doesNotMatch(catalog,/Ventana operativa · editable/);
assert.match(catalog,/Ventana operativa \(KPIs\) · Inicio → fin/);
assert.match(catalog,/gobierna[n]? KPIs/i);
assert.match(tracking,/DUE_IN_PERIOD/);
assert.match(metrics,/DUE_IN_PERIOD/);
assert.match(dashboardService,/operationalQuarterRepository\.listOverrides\(\)/);
assert.match(dashboardService,/vendorQuarterContext\(now, filters\.quarterCode, operationalQuarterOverrides\)/);
assert.match(certificationService,/vendorQuarterForDate\(item\.expirationDate, operationalQuarterOverrides\)/);
assert.match(sql,/DROP CONSTRAINT CK_OperationalQuarterConfig_DerivedWindow/);
assert.match(sql,/CK_OperationalQuarterConfig_MonthStart/);
assert.match(sql,/CK_OperationalQuarterConfig_MonthEnd/);
assert.match(legacySql,/CK_OperationalQuarterConfig_MonthStart/);
assert.match(legacySql,/NO volver a derivar ni sobrescribir ajustes manuales/);
console.log('Quarter Configuration V31.14: OK');
console.log('- Vendors conserva referencia y admite traslapes reales: OK');
console.log('- ventana operativa identifica inicio/fin y gobierna KPIs y filtros Q: OK');
console.log('- límites operativos siguen siendo meses completos, continuos y sin traslapes: OK');
console.log('- cambios de frontera invalidan snapshots afectados: OK');
