import assert from 'node:assert/strict';
import fs from 'node:fs';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'../..');
const read=(relative)=>fs.readFileSync(path.join(root,relative),'utf8');
const dashboard=read('src/pagesBBVATalent/dashboard/BBVADashboardPage.tsx');
const hook=read('src/pagesBBVATalent/hooks/useDashboard.ts');
const service=read('api/src/lib/bbvaDashboardService.ts');
const frontendTypes=read('src/pagesBBVATalent/types/dashboard.ts');
const backendTypes=read('api/src/lib/bbvaDashboardDomain.ts');
assert.match(hook,/refetchInterval:\s*20_000/);
assert.match(hook,/refetchOnWindowFocus:\s*true/);
assert.match(dashboard,/activeRecommendationIndex/);
assert.match(dashboard,/setInterval\(\(\)=>scrollToRecommendation\(activeRecommendationIndex\+1\),4200\)/);
assert.match(dashboard,/visibleRecommendations\.length<2/);
assert.doesNotMatch(dashboard,/visibleRecommendations\.length<3/);
assert.match(dashboard,/min-w-\[88%\]/);
assert.match(dashboard,/scale-\[\.975\]/);
assert.match(dashboard,/Carrusel de recomendaciones operativas/);
assert.match(dashboard,/recommendationUpdatedAt=query\.dataUpdatedAt/);
assert.match(dashboard,/última actualización/);
assert.match(dashboard,/Poner en marcha/);
assert.match(dashboard,/onDismiss=/);
assert.match(dashboard,/params\.set\('technology',item\.technology\)/);
assert.match(dashboard,/self-start overflow-hidden/);
assert.match(service,/technologyConcentrations/);
assert.match(service,/appendTechnologyRecommendations/);
assert.match(service,/concentrations\.slice\(0, 3\)/);
assert.match(service,/appendTechnologyRecommendations\(recommendations, attention, 'critical'/);
assert.match(service,/appendTechnologyRecommendations\(recommendations, attention, 'expired'/);
assert.match(service,/appendTechnologyRecommendations\(recommendations, attention, 'recertificationPending'/);
assert.match(service,/appendTechnologyRecommendations\(recommendations, attention, 'expiring'/);
assert.match(service,/appendTechnologyRecommendations\(recommendations, attention, 'pending'/);
assert.match(service,/id: 'coverage-gap'/);
assert.match(service,/id: 'talent-bank-active'/);
assert.match(service,/return recommendations;/);
assert.doesNotMatch(service,/return recommendations\.slice\(0, 6\)/);
assert.match(frontendTypes,/technology\?: string \| null/);
assert.match(backendTypes,/technology\?: string \| null/);
console.log('Live Recommendation Carousel V31.7: OK');
console.log('- carrusel automático visible desde 2 recomendaciones: OK');
console.log('- tarjetas con escala/opacidad sin desplazamiento vertical: OK');
console.log('- actualización automática del dashboard cada 20 s: OK');
console.log('- recomendaciones adicionales derivadas de concentraciones tecnológicas reales: OK');
console.log('- recomendaciones sin límite artificial de 6: OK');
console.log('- poner en marcha conserva tecnología/estado del foco: OK');
