import React, { useEffect, useMemo, useState } from 'react';
import { CalendarRange, ChevronDown, ChevronUp, Plus, RefreshCw, Save, Trash2 } from 'lucide-react';
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query';
import { BBVAAlert } from '../../componentsBBVATalent/BBVAAlert';
import { BBVAButton } from '../../componentsBBVATalent/BBVAButton';
import { BBVADatePicker } from '../../componentsBBVATalent/BBVADatePicker';
import { ConfirmDialog } from '../../componentsBBVATalent/ConfirmDialog';
import { operationalQuarterApi, type OperationalQuarterDraft, type OperationalQuarterItem } from '../api/operationalQuarterApi';

const dateLabel=(value:string)=>{const date=new Date(`${value}T12:00:00`);return Number.isNaN(date.getTime())?value:date.toLocaleDateString('es-MX',{day:'2-digit',month:'short',year:'numeric'});};
const draftOf=(item:OperationalQuarterItem):OperationalQuarterDraft=>({sourceStartDate:item.sourceStartDate,sourceEndDate:item.sourceEndDate,operationalStartDate:item.operationalStartDate,operationalEndDate:item.operationalEndDate});
const validIso=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value)&&!Number.isNaN(Date.parse(`${value}T00:00:00Z`));
type PendingDelete={kind:'period';item:OperationalQuarterItem}|{kind:'year';year:number;count:number}|null;

const derivedPreview=(sourceStartDate:string,sourceEndDate:string)=>{
  if(!validIso(sourceStartDate)||!validIso(sourceEndDate))return null;
  const start=new Date(`${sourceStartDate.slice(0,7)}-01T00:00:00Z`);
  if(!sourceStartDate.endsWith('-01'))start.setUTCMonth(start.getUTCMonth()+1);
  const end=new Date(`${sourceEndDate.slice(0,7)}-01T00:00:00Z`);end.setUTCMonth(end.getUTCMonth()+1);end.setUTCDate(0);
  return {startDate:start.toISOString().slice(0,10),endDate:end.toISOString().slice(0,10)};
};

export const OperationalQuarterCatalogPage:React.FC=()=>{
  const client=useQueryClient();
  const query=useQuery({queryKey:['bbva-operational-quarters'],queryFn:operationalQuarterApi.list});
  const [drafts,setDrafts]=useState<Record<string,OperationalQuarterDraft>>({});
  const [expandedYears,setExpandedYears]=useState<Set<number>>(new Set());
  const [newYear,setNewYear]=useState<number>(new Date().getFullYear()+1);
  const [pendingDelete,setPendingDelete]=useState<PendingDelete>(null);
  const [error,setError]=useState<string|null>(null);const [message,setMessage]=useState<string|null>(null);
  useEffect(()=>{if(!query.data?.items)return;setDrafts(Object.fromEntries(query.data.items.map((item)=>[item.code,draftOf(item)])));const years=[...new Set(query.data.items.map((item)=>item.year))];setExpandedYears((current)=>current.size?current:new Set(years));const max=Math.max(...years,new Date().getFullYear());setNewYear(max+1);},[query.data?.items]);
  const refreshAll=async()=>{await client.invalidateQueries({queryKey:['bbva-operational-quarters']});await client.invalidateQueries({queryKey:['bbva-dashboard']});await client.invalidateQueries({queryKey:['certification-tracking']});};
  const update=useMutation({mutationFn:({code,draft}:{code:string;draft:OperationalQuarterDraft})=>operationalQuarterApi.update(code,draft),onSuccess:async()=>{await refreshAll();setMessage('Periodo actualizado. Las fechas Vendors quedan como referencia y la ventana operativa guardada gobierna KPIs, Seguimiento, Métricas y Panel.');}});
  const createYear=useMutation({mutationFn:(year:number)=>operationalQuarterApi.createYear(year),onSuccess:async(result)=>{await refreshAll();setExpandedYears((current)=>new Set([...current,result.year]));setNewYear(result.year+1);setMessage(`Año ${result.year} agregado. Ajusta y confirma las fechas reales de Vendors cuando estén disponibles.`);}});
  const deletePeriod=useMutation({mutationFn:(code:string)=>operationalQuarterApi.remove(code),onSuccess:async(result)=>{await refreshAll();setPendingDelete(null);setMessage(`Periodo ${result.deleted} eliminado.`);}});
  const deleteYear=useMutation({mutationFn:(year:number)=>operationalQuarterApi.removeYear(year),onSuccess:async(result)=>{await refreshAll();setExpandedYears((current)=>{const next=new Set(current);next.delete(result.deletedYear);return next;});setPendingDelete(null);setMessage(`Año ${result.deletedYear} eliminado junto con sus periodos configurados.`);}});
  const busy=update.isPending||createYear.isPending||deletePeriod.isPending||deleteYear.isPending;const items=useMemo(()=>query.data?.items??[],[query.data?.items]);
  const byYear=useMemo(()=>{const map=new Map<number,OperationalQuarterItem[]>();for(const item of items){const bucket=map.get(item.year)??[];bucket.push(item);map.set(item.year,bucket);}for(const bucket of map.values())bucket.sort((a,b)=>a.quarter-b.quarter);return [...map.entries()].sort((a,b)=>b[0]-a[0]);},[items]);
  const save=async(item:OperationalQuarterItem)=>{const draft=drafts[item.code];if(!draft)return;try{setError(null);setMessage(null);await update.mutateAsync({code:item.code,draft});}catch(e){setError((e as Error).message);}};
  const addYear=async()=>{try{setError(null);setMessage(null);await createYear.mutateAsync(newYear);}catch(e){setError((e as Error).message);}};
  const confirmDelete=async()=>{if(!pendingDelete)return;try{setError(null);setMessage(null);if(pendingDelete.kind==='period')await deletePeriod.mutateAsync(pendingDelete.item.code);else await deleteYear.mutateAsync(pendingDelete.year);}catch(e){setPendingDelete(null);setError((e as Error).message);}};
  const toggleYear=(year:number)=>setExpandedYears((current)=>{const next=new Set(current);if(next.has(year))next.delete(year);else next.add(year);return next;});
  return <div className="space-y-3 animate-fade-in">
    <section className="rounded-2xl border border-slate-200 bg-white px-4 py-3 shadow-sm">
      <div className="text-[9px] font-semibold uppercase tracking-[.08em] text-blue-600">Configuración de periodos</div>
      <div className="mt-1 flex flex-wrap items-start justify-between gap-3"><div><h1 className="text-lg font-semibold text-slate-950">PERIODOS OPERATIVOS (Q)</h1><p className="mt-1 max-w-4xl text-[10.5px] text-slate-500">Las fechas Vendors son referencia de negocio y pueden traslaparse. La ventana operativa se configura por separado y es la que gobierna KPIs, Seguimiento, Métricas, Panel y readiness.</p></div><div className="flex flex-wrap items-center gap-2"><input type="number" min={2020} max={2100} value={newYear} onChange={(event)=>setNewYear(Number(event.target.value))} className="h-8 w-24 rounded-lg border border-slate-300 px-2 text-[10.5px] font-semibold outline-none focus:border-blue-500" aria-label="Año a agregar"/><BBVAButton variant="primary" size="sm" icon={<Plus className="h-3.5 w-3.5"/>} disabled={busy} onClick={()=>void addYear()}>Agregar año</BBVAButton><BBVAButton variant="secondary" size="sm" icon={<RefreshCw className={`h-3.5 w-3.5 ${query.isFetching?'animate-spin':''}`}/>} onClick={()=>void query.refetch()}>Actualizar</BBVAButton></div></div>
    </section>
    {message?<BBVAAlert tone="success" onClose={()=>setMessage(null)}>{message}</BBVAAlert>:null}{error?<BBVAAlert tone="error" onClose={()=>setError(null)}>{error}</BBVAAlert>:null}{query.error?<BBVAAlert tone="error">{(query.error as Error).message}</BBVAAlert>:null}
    <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm">
      <div className="border-b border-slate-100 px-4 py-3"><div className="flex items-center gap-2"><CalendarRange className="h-4 w-4 text-blue-600"/><h2 className="text-sm font-semibold text-slate-950">Calendario BBVA</h2></div><p className="mt-1 text-[9.5px] text-slate-500">Ejemplo: Vendors puede indicar Q4 del 23 de septiembre al 3 de enero y traslaparse con Q1. Puedes mantener operativamente Q4 del 1 de octubre al 31 de diciembre y Q1 desde el 1 de enero. Las ventanas operativas deben ser mensuales, continuas y sin traslapes.</p></div>
      {query.isLoading?<div className="p-8 text-center text-xs text-slate-500">Cargando periodos...</div>:<div>{byYear.map(([year,yearItems])=>{const open=expandedYears.has(year);const current=yearItems.some((item)=>item.current);const yearDeletable=yearItems.some((item)=>item.yearDeletable);return <div key={year} className="border-b border-slate-100 last:border-b-0"><div className="flex items-center justify-between gap-2 bg-slate-50/70 px-4 py-2.5"><button type="button" onClick={()=>toggleYear(year)} className="flex min-w-0 flex-1 items-center justify-between text-left"><div className="flex items-center gap-2"><span className="text-sm font-semibold text-slate-900">{year}</span><span className="rounded-full bg-slate-100 px-2 py-0.5 text-[8.5px] font-semibold text-slate-600">{yearItems.length} periodos</span>{current?<span className="rounded-full bg-blue-50 px-2 py-0.5 text-[8.5px] font-semibold text-blue-700">Año actual</span>:null}</div>{open?<ChevronUp className="h-4 w-4 text-slate-500"/>:<ChevronDown className="h-4 w-4 text-slate-500"/>}</button>{yearDeletable?<BBVAButton variant="tableDanger" size="sm" icon={<Trash2 className="h-3.5 w-3.5"/>} disabled={busy} onClick={()=>setPendingDelete({kind:'year',year,count:yearItems.length})}>Eliminar año</BBVAButton>:null}</div>{open?<div className="divide-y divide-slate-100">{yearItems.map((item)=>{const draft=drafts[item.code]??draftOf(item);const changed=draft.sourceStartDate!==item.sourceStartDate||draft.sourceEndDate!==item.sourceEndDate||draft.operationalStartDate!==item.operationalStartDate||draft.operationalEndDate!==item.operationalEndDate;const preview=derivedPreview(draft.sourceStartDate,draft.sourceEndDate);return <div key={item.code} className="grid gap-3 p-4 2xl:grid-cols-[160px_minmax(420px,1fr)_minmax(320px,.8fr)_auto] 2xl:items-end">
        <div><div className="flex flex-wrap items-center gap-2"><span className="text-sm font-semibold text-slate-950">Periodo {item.quarter}</span>{item.current?<span className="rounded-full bg-blue-50 px-2 py-0.5 text-[8.5px] font-semibold text-blue-700">Actual</span>:null}{!item.sourceConfigured?<span className="rounded-full bg-amber-50 px-2 py-0.5 text-[8.5px] font-semibold text-amber-700">Vendors por confirmar</span>:null}{!item.synchronized?<span className="rounded-full bg-rose-50 px-2 py-0.5 text-[8.5px] font-semibold text-rose-700">Ajuste operativo</span>:null}</div><div className="mt-1 text-[9px] text-slate-400">{item.code}</div></div>
        <div><div className="mb-1 text-[8.5px] font-semibold uppercase tracking-[.05em] text-slate-500">Ventana Vendors · Inicio → fin</div><div className="grid gap-2 sm:grid-cols-2"><BBVADatePicker value={draft.sourceStartDate} onChange={(value)=>setDrafts((currentDrafts)=>({...currentDrafts,[item.code]:{...draft,sourceStartDate:value}}))} disabled={busy} ariaLabel={`Inicio Vendors ${item.code}`}/><BBVADatePicker value={draft.sourceEndDate} onChange={(value)=>setDrafts((currentDrafts)=>({...currentDrafts,[item.code]:{...draft,sourceEndDate:value}}))} disabled={busy} ariaLabel={`Fin Vendors ${item.code}`}/></div><div className="mt-1 text-[9px] text-slate-400">Referencia Vendors (solo informativa, no gobierna KPIs) · inicio → fin: {dateLabel(item.sourceStartDate)} → {dateLabel(item.sourceEndDate)}</div></div>
        <div><div className="mb-1 text-[8.5px] font-semibold uppercase tracking-[.05em] text-slate-500">Ventana operativa (KPIs) · Inicio → fin</div><div className="grid gap-2 sm:grid-cols-2"><BBVADatePicker value={draft.operationalStartDate} onChange={(value)=>setDrafts((currentDrafts)=>({...currentDrafts,[item.code]:{...draft,operationalStartDate:value}}))} disabled={busy} ariaLabel={`Inicio operativo ${item.code}`}/><BBVADatePicker value={draft.operationalEndDate} onChange={(value)=>setDrafts((currentDrafts)=>({...currentDrafts,[item.code]:{...draft,operationalEndDate:value}}))} disabled={busy} ariaLabel={`Fin operativo ${item.code}`}/></div><div className="mt-1 text-[9px] text-slate-400">Estas fechas gobiernan KPIs, vencimientos y seguimiento. Sugerencia Vendors · inicio → fin: {preview?`${dateLabel(preview.startDate)} → ${dateLabel(preview.endDate)}`:'No disponible'}</div></div>
        <div className="flex justify-end gap-2">{item.deletable?<BBVAButton variant="tableDanger" size="sm" icon={<Trash2 className="h-3.5 w-3.5"/>} disabled={busy} onClick={()=>setPendingDelete({kind:'period',item})}>Eliminar</BBVAButton>:null}<BBVAButton variant="primary" size="sm" icon={<Save className="h-3.5 w-3.5"/>} disabled={busy||!changed} onClick={()=>void save(item)}>Guardar</BBVAButton></div>
      </div>;})}</div>:null}</div>;})}</div>}
    </section>
    <ConfirmDialog open={Boolean(pendingDelete)} title={pendingDelete?.kind==='year'?`Eliminar año ${pendingDelete.year}`:'Eliminar periodo'} message={pendingDelete?.kind==='year'?`Se eliminarán los ${pendingDelete.count} periodos configurados de ${pendingDelete.year}. Sólo se permite eliminar el año futuro más reciente.`:pendingDelete?.kind==='period'?`Se eliminará ${pendingDelete.item.code}. El periodo actual, históricos y periodos base están protegidos.`:''} confirmLabel={pendingDelete?.kind==='year'?'Eliminar año':'Eliminar periodo'} tone="danger" busy={deletePeriod.isPending||deleteYear.isPending} onCancel={()=>setPendingDelete(null)} onConfirm={()=>void confirmDelete()}/>
  </div>;
};

