import React,{useMemo,useState} from 'react';
import { Pencil,Plus,Power,RefreshCw,Search,Trash2 } from 'lucide-react';
import { BBVAActionMenu } from '../../componentsBBVATalent/BBVAActionMenu';
import { BBVAAlert } from '../../componentsBBVATalent/BBVAAlert';
import { BBVAButton } from '../../componentsBBVATalent/BBVAButton';
import { BBVASearchableSelect } from '../../componentsBBVATalent/BBVASearchableSelect';
import { ConfirmDialog } from '../../componentsBBVATalent/ConfirmDialog';
import { useCreateStructure,useDeleteStructure,useStructureCatalog,useStructureStatus,useUpdateStructure } from '../hooks/useStructureCatalog';
import { displayStructure } from '../lib/bbvaDisplayFormat';
import type { StructureLevel,StructurePayload,StructureRecord,StructureStatus } from '../types/structureCatalog';

const empty:StructurePayload={level:2,parentId:null,name:'',description:''};
export const StructureCatalogPage:React.FC=()=>{
 const [search,setSearch]=useState('');const [status,setStatus]=useState<StructureStatus|'ALL'>('ACTIVE');const [editing,setEditing]=useState<StructureRecord|null>(null);const [draft,setDraft]=useState<StructurePayload>(empty);const [message,setMessage]=useState<string|null>(null);const [error,setError]=useState<string|null>(null);const [pending,setPending]=useState<{kind:'status'|'delete';item:StructureRecord;next?:StructureStatus}|null>(null);
 const query=useStructureCatalog(search,status);const create=useCreateStructure();const update=useUpdateStructure();const statusMutation=useStructureStatus();const remove=useDeleteStructure();const items=query.data?.items??[];const level2=useMemo(()=>items.filter(x=>x.level===2&&x.status==='ACTIVE'),[items]);
 const start=(item?:StructureRecord)=>{setEditing(item??null);setDraft(item?{level:item.level,parentId:item.parentId,name:item.name,description:item.description}:empty);};
 const save=async()=>{try{setError(null);if(editing)await update.mutateAsync({id:editing.id,payload:draft});else await create.mutateAsync(draft);setMessage(editing?'Estructura actualizada.':'Estructura creada.');start();}catch(e){setError((e as Error).message);}};
 const confirm=async()=>{if(!pending)return;try{setError(null);if(pending.kind==='delete')await remove.mutateAsync(pending.item.id);else await statusMutation.mutateAsync({id:pending.item.id,status:pending.next!});setMessage('Operación completada.');setPending(null);}catch(e){setError((e as Error).message);setPending(null);}};
 return <div className="space-y-3 animate-fade-in">
  <div className="flex flex-wrap items-center justify-between gap-2"><div><h1 className="text-lg font-semibold text-slate-950">Estructuras BBVA</h1><p className="text-[10px] text-slate-500">Catálogo jerárquico único para Estructura nivel 2 y nivel 3.</p></div><BBVAButton variant="primary" icon={<Plus className="h-3.5 w-3.5"/>} onClick={()=>start()}>Agregar estructura</BBVAButton></div>
  {message?<BBVAAlert tone="success" onClose={()=>setMessage(null)}>{message}</BBVAAlert>:null}{error?<BBVAAlert tone="error" onClose={()=>setError(null)}>{error}</BBVAAlert>:null}
  <section className="grid gap-2 rounded-2xl border border-slate-200 bg-white p-3 lg:grid-cols-[1fr_180px]"><div className="relative"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar estructura o descripción" className="h-9 w-full rounded-xl border border-slate-300 pl-8 pr-3 text-[11px] outline-none focus:border-blue-500"/></div><BBVASearchableSelect value={status} onChange={v=>setStatus(v as any)} options={[{value:'ACTIVE',label:'Activas'},{value:'INACTIVE',label:'Inactivas'},{value:'ALL',label:'Todas'}]} ariaLabel="Estado"/></section>
  {(editing!==null||draft.name!==''||draft.level!==2||draft.description)?<section className="bbva-live-panel rounded-2xl border border-blue-100 bg-white p-4 shadow-sm"><div className="mb-3 text-sm font-semibold">{editing?'Editar estructura':'Nueva estructura'}</div><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-4"><BBVASearchableSelect value={String(draft.level)} onChange={v=>setDraft(d=>({...d,level:Number(v) as StructureLevel,parentId:Number(v)===2?null:d.parentId}))} options={[{value:'2',label:'Nivel 2'},{value:'3',label:'Nivel 3'}]} ariaLabel="Nivel" disabled={Boolean(editing)}/>{draft.level===3?<BBVASearchableSelect value={draft.parentId??''} onChange={v=>setDraft(d=>({...d,parentId:v||null}))} options={[{value:'',label:'Seleccionar nivel 2'},...level2.map(x=>({value:x.id,label:displayStructure(x.name)}))]} ariaLabel="Estructura nivel 2"/>:<div/>}<input value={draft.name} onChange={e=>setDraft(d=>({...d,name:e.target.value}))} placeholder="Nombre" className="h-9 rounded-xl border border-slate-300 px-3 text-[11px] outline-none focus:border-blue-500"/><input value={draft.description??''} onChange={e=>setDraft(d=>({...d,description:e.target.value}))} placeholder="Descripción" className="h-9 rounded-xl border border-slate-300 px-3 text-[11px] outline-none focus:border-blue-500"/></div><div className="mt-3 flex justify-end gap-2"><BBVAButton variant="secondary" onClick={()=>{setEditing(null);setDraft(empty);}}>Cancelar</BBVAButton><BBVAButton variant="primary" onClick={()=>void save()} disabled={!draft.name.trim()||(draft.level===3&&!draft.parentId)||create.isPending||update.isPending}>{create.isPending||update.isPending?'Guardando...':'Guardar'}</BBVAButton></div></section>:null}
  <div className="overflow-visible rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-[10.5px]"><thead className="bg-slate-50 text-[9px] uppercase text-slate-500"><tr><th className="px-3 py-2">Nivel</th><th className="px-3 py-2">Nombre</th><th className="px-3 py-2">Depende de</th><th className="px-3 py-2">Descripción</th><th className="px-3 py-2 text-center">Usos</th><th className="px-3 py-2">Estado</th><th className="px-3 py-2 text-right">Acciones</th></tr></thead><tbody className="divide-y divide-slate-100">{items.map(item=><tr key={item.id} className="hover:bg-slate-50"><td className="px-3 py-2 font-semibold">Nivel {item.level}</td><td className="px-3 py-2 font-semibold">{displayStructure(item.name)}</td><td className="px-3 py-2 text-slate-600">{item.parentName?displayStructure(item.parentName):'—'}</td><td className="px-3 py-2 text-slate-600">{item.description||'—'}</td><td className="px-3 py-2 text-center font-semibold">{item.usageCount}</td><td className="px-3 py-2"><span className={`rounded-full px-2 py-1 text-[9px] font-semibold ${item.status==='ACTIVE'?'bg-emerald-50 text-emerald-700':'bg-slate-100 text-slate-600'}`}>{item.status==='ACTIVE'?'Activa':'Inactiva'}</span></td><td className="px-3 py-2 text-right"><BBVAActionMenu items={item.status==='ACTIVE'?[{id:'edit',label:'Editar',icon:Pencil,onClick:()=>start(item)},{id:'inactive',label:'Inactivar',icon:Power,onClick:()=>setPending({kind:'status',item,next:'INACTIVE'})}]:[{id:'edit',label:'Editar',icon:Pencil,onClick:()=>start(item)},{id:'active',label:'Activar',icon:RefreshCw,onClick:()=>setPending({kind:'status',item,next:'ACTIVE'})},{id:'delete',label:'Eliminar',icon:Trash2,tone:'danger' as const,onClick:()=>setPending({kind:'delete',item})}]}/></td></tr>)}</tbody></table></div>{!items.length?<div className="p-8 text-center text-xs text-slate-500">No hay estructuras con estos filtros.</div>:null}</div>
  <ConfirmDialog open={Boolean(pending)} title={pending?.kind==='delete'?'Eliminar estructura':pending?.next==='ACTIVE'?'Activar estructura':'Inactivar estructura'} message={pending?`Se actualizará “${pending.item.name}”.`:''} confirmLabel="Confirmar" tone={pending?.kind==='delete'?'danger':'warning'} busy={statusMutation.isPending||remove.isPending} onCancel={()=>setPending(null)} onConfirm={()=>void confirm()}/>
 </div>;
};
