import React, { useMemo, useState } from 'react';
import { AlertTriangle, Award, RefreshCw, ShieldCheck, UsersRound } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { BBVAAlert } from '../../componentsBBVATalent/BBVAAlert';
import { BBVAButton } from '../../componentsBBVATalent/BBVAButton';
import { BBVAChartCard } from '../../componentsBBVATalent/BBVAChartCard';
import { BBVAEmptyState } from '../../componentsBBVATalent/BBVAEmptyState';
import { BBVAHistoricalMetricPanel } from '../../componentsBBVATalent/BBVAHistoricalMetricPanel';
import { BBVAHorizontalBars } from '../../componentsBBVATalent/BBVAHorizontalBars';
import { BBVAMetricCard } from '../../componentsBBVATalent/BBVAMetricCard';
import { BBVAMetricsSkeleton } from '../../componentsBBVATalent/BBVAMetricsSkeleton';
import { BBVAQuarterSelector } from '../../componentsBBVATalent/BBVAQuarterSelector';
import { BBVASearchableSelect } from '../../componentsBBVATalent/BBVASearchableSelect';
import { useBBVAListQueryState } from '../hooks/useBBVAListQueryState';
import { useBbvaDashboard } from '../hooks/useDashboard';
import { dashboardMetricDefinitions } from '../lib/dashboardMetricDefinitions';
import { sentenceCaseData } from '../lib/bbvaDisplayFormat';
import type { DashboardHistoricalMetricKey, DashboardMetricComparison } from '../types/dashboard';

interface MetricsFilterState extends Record<string,string> {
  technologyId:string; profileId:string; technologyProfile:string; certificationId:string;
  bbvaStructureLevel2:string; bbvaStructureLevel3:string; quarterCode:string; deliveryManager:string;
  certificationStatus:string; talentType:string; fromDate:string; toDate:string; search:string;
  historyDays:string; comparisonDays:string;
}
const initialFilters:MetricsFilterState={technologyId:'',profileId:'',technologyProfile:'',certificationId:'',bbvaStructureLevel2:'',bbvaStructureLevel3:'',quarterCode:'',deliveryManager:'',certificationStatus:'',talentType:'',fromDate:'',toDate:'',search:'',historyDays:'90',comparisonDays:'7'};
const statusOptions=[{value:'',label:'Todos los estados de certificación'},{value:'VALID',label:'Vigentes'},{value:'EXPIRING',label:'Vencen en el Q'},{value:'EXPIRED',label:'Vencidas antes del Q'},{value:'RECERTIFICATION_PENDING',label:'Recertificación pendiente'},{value:'PENDING',label:'Pendientes'},{value:'FAILED',label:'Reprobadas'}];
const universeOptions=[{value:'',label:'Todo el universo'},{value:'ACADEMY',label:'Academia'},{value:'PROSPECT',label:'Prospectos'},{value:'FORMER_COLLABORATOR',label:'Excolaboradores'},{value:'BBVA_EXIT',label:'Bajas de BBVA'}];
function comparisonText(comparison?:DashboardMetricComparison){if(!comparison)return undefined;const sign=comparison.delta>0?'+':'';const unit=comparison.unit==='PERCENTAGE_POINTS'?' pp':'';return `${sign}${comparison.delta.toLocaleString('es-MX',{maximumFractionDigits:2})}${unit} vs ${comparison.previousSnapshotDate}`;}

export const CertificationMetricsPage:React.FC=()=>{
  const navigate=useNavigate();
  const {state:filters,update:updateFilters}=useBBVAListQueryState(initialFilters);
  const [historyMetric,setHistoryMetric]=useState<DashboardHistoricalMetricKey>('coveragePercent');
  const [scoreDetailId,setScoreDetailId]=useState<string|null>(null);
  const query=useBbvaDashboard(filters); const data=query.data; const cards=data?.cards;
  const update=(key:keyof MetricsFilterState,value:string)=>updateFilters({[key]:value} as Partial<MetricsFilterState>);
  React.useEffect(()=>{if(data?.vendorQuarter.selectedCode&&!filters.quarterCode)update('quarterCode',data.vendorQuarter.selectedCode);},[data?.vendorQuarter.selectedCode,filters.quarterCode]);
  const filteredContext=Boolean(filters.technologyId||filters.certificationStatus||filters.talentType||filters.bbvaStructureLevel2||filters.bbvaStructureLevel3||filters.certificationId||filters.profileId||filters.technologyProfile);
  const technologyBars=useMemo(()=>(data?.technologyDistribution??[]).map((item)=>({key:item.technologyId??'',label:sentenceCaseData(item.label),value:item.value})),[data?.technologyDistribution]);
  const maxTech=Math.max(1,...technologyBars.map((item)=>item.value));
  if(query.error)return <BBVAAlert tone="error">{(query.error as Error).message}</BBVAAlert>;
  return <div className="space-y-3 animate-fade-in">
    <section className="bbva-live-panel rounded-2xl border border-slate-200 bg-slate-50/70 p-3">
      <div className="mb-2 flex items-center justify-between"><div><div className="text-[9px] font-semibold uppercase tracking-[.06em] text-blue-600">Métricas por Q</div><div className="text-[10px] text-slate-500">Vigencia, cobertura y vencimientos responden al Q seleccionado.</div></div><BBVAButton variant="secondary" size="sm" icon={<RefreshCw className={`h-3.5 w-3.5 ${query.isFetching?'animate-spin':''}`}/>} onClick={()=>void query.refetch()}>Actualizar</BBVAButton></div>
      <div className="grid gap-2 md:grid-cols-2 xl:grid-cols-5">
        <BBVASearchableSelect value={filters.technologyId} onChange={(v)=>update('technologyId',v)} options={[{value:'',label:'Todas las tecnologías'},...(data?.filters.technologies??[]).map((item)=>({value:item.id,label:sentenceCaseData(item.name)}))]} ariaLabel="Tecnología"/>
        <BBVASearchableSelect value={filters.certificationStatus} onChange={(v)=>update('certificationStatus',v)} options={statusOptions} ariaLabel="Estado de certificación"/>
        <BBVASearchableSelect value={filters.talentType} onChange={(v)=>update('talentType',v)} options={universeOptions} ariaLabel="Universo"/>
        <BBVASearchableSelect value={filters.bbvaStructureLevel2} onChange={(v)=>update('bbvaStructureLevel2',v)} options={[{value:'',label:'Estructura nivel 2'},...(data?.filters.bbvaStructuresLevel2??[]).map((value)=>({value,label:sentenceCaseData(value)}))]} ariaLabel="Estructura nivel 2"/>
        <BBVASearchableSelect value={filters.bbvaStructureLevel3} onChange={(v)=>update('bbvaStructureLevel3',v)} options={[{value:'',label:'Estructura nivel 3'},...(data?.filters.bbvaStructuresLevel3??[]).map((value)=>({value,label:sentenceCaseData(value)}))]} ariaLabel="Estructura nivel 3"/>
      </div>
    </section>

    {data?.vendorQuarter.quarters?.length?<BBVAQuarterSelector currentCode={data.vendorQuarter.currentCode} selectedCode={data.vendorQuarter.selectedCode} referenceDate={data.vendorQuarter.referenceDate} progressPercent={data.vendorQuarter.progressPercent} daysToEnd={data.vendorQuarter.daysToSelectedEnd} years={data.vendorQuarter.years} quarters={data.vendorQuarter.quarters} onChange={(code)=>update('quarterCode',code)}/>:null}

    {query.isLoading||!data||!cards?<BBVAMetricsSkeleton cards={5}/>:<>
      <div className="grid grid-cols-[repeat(auto-fit,minmax(180px,1fr))] gap-2">
        <BBVAMetricCard label="Promedio certificaciones" value={cards.certificationAverage??'—'} icon={<Award className="h-4 w-4"/>} tone="blue" help={dashboardMetricDefinitions.certificationAverage} supportingText={`${cards.certificationScoreBase} resultados válidos`}/>
        <BBVAMetricCard label={`Cobertura · ${data.vendorQuarter.selectedCode??'Q'}`} value={`${cards.coveragePercent}%`} icon={<ShieldCheck className="h-4 w-4"/>} tone="emerald" help={dashboardMetricDefinitions.coveragePercent} supportingText={`${cards.certificationsApplicable} aplicables`} trendText={comparisonText(data.history.comparisons.coveragePercent)}/>
        <BBVAMetricCard label={`Vencen en ${data.vendorQuarter.selectedCode??'Q'}`} value={data.quarterExpirations.length} icon={<AlertTriangle className="h-4 w-4"/>} tone={data.quarterExpirations.length?'amber':'emerald'} supportingText="Fechas dentro del Q" trendText={comparisonText(data.history.comparisons.expiring)} onAction={()=>update('certificationStatus','EXPIRING')} actionLabel="Filtrar"/>
        <BBVAMetricCard label="Pendientes" value={cards.pending} icon={<Award className="h-4 w-4"/>} tone={cards.pending?'blue':'emerald'} supportingText="Sin cobertura vigente" trendText={comparisonText(data.history.comparisons.pending)} onAction={()=>update('certificationStatus','PENDING')} actionLabel="Filtrar"/>
        <BBVAMetricCard label="Críticos 2/2" value={cards.vendorExitRequired} icon={<UsersRound className="h-4 w-4"/>} tone={cards.vendorExitRequired?'rose':'emerald'} supportingText={`${cards.recertificationPending} recertificaciones`} trendText={comparisonText(data.history.comparisons.vendorExitRequired)} onAction={()=>navigate('/bbva/certifications/tracking?critical=OPEN')} actionLabel="Resolver"/>
      </div>

      <section className="bbva-live-panel overflow-hidden rounded-2xl border border-blue-100 bg-white shadow-sm">
        <div className="flex items-center justify-between gap-3 border-b border-slate-100 px-4 py-3"><div><h2 className="text-sm font-semibold text-slate-950">Certificaciones que vencen en {data.vendorQuarter.selectedCode}</h2><p className="mt-0.5 text-[9.5px] text-slate-500">Listado completo del Q seleccionado para los filtros actuales.</p></div><span className="rounded-full bg-blue-50 px-3 py-1 text-[10px] font-semibold text-blue-700">{data.quarterExpirations.length} vencimientos</span></div>
        {data.quarterExpirations.length?<div className="max-h-[300px] overflow-auto"><table className="w-full min-w-[760px] text-left text-[10px]"><thead className="sticky top-0 bg-slate-50 text-[8.5px] font-semibold uppercase text-slate-500"><tr><th className="px-3 py-2">Colaborador</th><th className="px-3 py-2">Certificación</th><th className="px-3 py-2">Vencimiento</th><th className="px-3 py-2 text-right">Acción</th></tr></thead><tbody className="divide-y divide-slate-100">{data.quarterExpirations.map((item)=><tr key={`${item.personId}-${item.certificationId}-${item.expirationDate}`} className="hover:bg-blue-50/25"><td className="px-3 py-2 font-semibold">{sentenceCaseData(item.fullName)}</td><td className="px-3 py-2">{sentenceCaseData(item.certificationName)}</td><td className="px-3 py-2 tabular-nums">{item.expirationDate}</td><td className="px-3 py-2 text-right">{item.collaboratorId?<BBVAButton variant="table" size="sm" onClick={()=>navigate(`/bbva/collaborators/${item.collaboratorId}/certifications`)}>Revisar</BBVAButton>:null}</td></tr>)}</tbody></table></div>:<BBVAEmptyState compact title="Sin vencimientos en el Q" description="No existen certificaciones con fecha de vencimiento dentro del Q seleccionado."/>}
      </section>

      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-4 py-3"><h2 className="text-sm font-semibold text-slate-950">Promedio actual por certificación</h2><p className="mt-0.5 text-[9.5px] text-slate-500">Una calificación válida más reciente por persona y certificación. No pondera intentos adicionales.</p></div><div className="grid gap-2 p-3 sm:grid-cols-2 xl:grid-cols-4">{data.certificationScores.length?data.certificationScores.map((item)=><button key={item.certificationId} type="button" onClick={()=>setScoreDetailId(scoreDetailId===item.certificationId?null:item.certificationId)} className={`bbva-live-card rounded-xl border p-3 text-left ${scoreDetailId===item.certificationId?'border-blue-400 bg-blue-50':'border-slate-200 bg-white hover:border-blue-200'}`}><div className="truncate text-[10px] font-semibold text-slate-800">{sentenceCaseData(item.certificationName)}</div><div className="mt-2 text-2xl font-semibold tabular-nums text-blue-700">{item.average.toFixed(2)}</div><div className="mt-1 text-[9px] text-slate-500">{item.peopleCount} colaboradores · Ver detalle</div></button>):<div className="col-span-full"><BBVAEmptyState compact title="Sin calificaciones válidas" description="No existen calificaciones configuradas para el universo y filtros actuales."/></div>}</div>{scoreDetailId?<div className="border-t border-slate-100 p-3"><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-[10px]"><thead className="bg-slate-50 text-[8.5px] uppercase text-slate-500"><tr><th className="px-3 py-2">Colaborador</th><th className="px-3 py-2">Resultado</th><th className="px-3 py-2 text-center">Calificación</th><th className="px-3 py-2">Fecha</th><th className="px-3 py-2 text-center">Intento</th></tr></thead><tbody className="divide-y divide-slate-100">{data.certificationScoreDetails.filter((row)=>row.certificationId===scoreDetailId).map((row)=><tr key={`${row.personId}-${row.certificationId}`}><td className="px-3 py-2 font-medium">{sentenceCaseData(row.fullName)}</td><td className="px-3 py-2">{sentenceCaseData(row.result)}</td><td className="px-3 py-2 text-center font-semibold">{row.score10.toFixed(2)}</td><td className="px-3 py-2">{row.applicationDate??'—'}</td><td className="px-3 py-2 text-center">{row.attemptNumber??'—'}</td></tr>)}</tbody></table></div></div>:null}</section>

      <div className="grid gap-3 xl:grid-cols-2"><BBVAChartCard title={`Distribución tecnológica · ${data.vendorQuarter.selectedCode}`} description="Selecciona una tecnología para actualizar el universo."><BBVAHorizontalBars items={technologyBars} max={maxTech} selectedKey={filters.technologyId} onSelect={(id)=>update('technologyId',filters.technologyId===id?'':id)}/></BBVAChartCard>{!filteredContext?<BBVAHistoricalMetricPanel history={data.history} metric={historyMetric} onMetricChange={setHistoryMetric} allowedMetrics={['coveragePercent','expiring','expired','recertificationPending','pending','vendorReadyPercent','vendorPending','vendorExitRequired']} title={`Evolución histórica · ${data.vendorQuarter.selectedCode}`}/>:<BBVAChartCard title="Histórico del Q" description="El histórico sólo compara snapshots del mismo Q y del universo global."><BBVAEmptyState compact title="Quita filtros para comparar" description="Así evitamos comparar universos distintos."/></BBVAChartCard>}</div>

      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="flex items-center justify-between border-b border-slate-100 px-4 py-3"><div><h2 className="text-sm font-semibold text-slate-950">Colaboradores a revisar</h2><p className="text-[9.5px] text-slate-500">Incluye estructura BBVA nivel 2 y 3.</p></div><BBVAButton variant="table" size="sm" onClick={()=>navigate('/bbva/certifications/tracking')}>Seguimiento</BBVAButton></div><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-[10px]"><thead className="bg-slate-50 text-[8.5px] font-semibold uppercase text-slate-500"><tr><th className="px-3 py-2">Colaborador</th><th className="px-3 py-2">Tecnología</th><th className="px-3 py-2">Estructura nivel 2</th><th className="px-3 py-2">Estructura nivel 3</th><th className="px-3 py-2 text-center">Próximas</th><th className="px-3 py-2 text-center">Pendientes</th><th className="px-3 py-2 text-right">Acción</th></tr></thead><tbody className="divide-y divide-slate-100">{data.attention.filter((row)=>row.critical+row.expired+row.recertificationPending+row.expiring+row.pending>0).slice(0,15).map((row)=><tr key={row.collaboratorId} className="hover:bg-slate-50"><td className="px-3 py-2"><div className="font-semibold">{sentenceCaseData(row.fullName)}</div><div className="text-[9px] text-slate-400">{sentenceCaseData(row.profile)}</div></td><td className="px-3 py-2">{sentenceCaseData(row.technology)}</td><td className="px-3 py-2">{sentenceCaseData(row.bbvaStructureLevel2)}</td><td className="px-3 py-2">{sentenceCaseData(row.bbvaStructureLevel3)}</td><td className="px-3 py-2 text-center font-semibold text-amber-700">{row.expiring}</td><td className="px-3 py-2 text-center font-semibold text-blue-700">{row.pending}</td><td className="px-3 py-2 text-right"><BBVAButton variant="table" size="sm" onClick={()=>navigate(`/bbva/collaborators/${row.collaboratorId}/certifications`)}>Revisar</BBVAButton></td></tr>)}</tbody></table></div></section>
    </>}
  </div>;
};
