import React, { useMemo, useState } from 'react';
import { AlertTriangle, Award, CalendarClock, RefreshCw, ShieldCheck, UsersRound } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { BBVAAlert } from '../../componentsBBVATalent/BBVAAlert';
import { BBVAButton } from '../../componentsBBVATalent/BBVAButton';
import { BBVAChartCard } from '../../componentsBBVATalent/BBVAChartCard';
import { BBVAEmptyState } from '../../componentsBBVATalent/BBVAEmptyState';
import { BBVAFilterBar } from '../../componentsBBVATalent/BBVAFilterBar';
import { BBVAHistoricalMetricPanel } from '../../componentsBBVATalent/BBVAHistoricalMetricPanel';
import { BBVAHorizontalBars } from '../../componentsBBVATalent/BBVAHorizontalBars';
import { BBVAMetricCard } from '../../componentsBBVATalent/BBVAMetricCard';
import { BBVAPagination } from '../../componentsBBVATalent/BBVAPagination';
import { BBVAMetricsSkeleton } from '../../componentsBBVATalent/BBVAMetricsSkeleton';
import { BBVASearchableSelect } from '../../componentsBBVATalent/BBVASearchableSelect';
import { BBVAMultiSelect } from '../../componentsBBVATalent/BBVAMultiSelect';
import { BBVAStructureFilter } from '../../componentsBBVATalent/BBVAStructureFilter';
import { useBBVAListQueryState } from '../hooks/useBBVAListQueryState';
import { useBbvaDashboard } from '../hooks/useDashboard';
import { useStructureOptions } from '../hooks/useStructureCatalog';
import { dashboardMetricDefinitions } from '../lib/dashboardMetricDefinitions';
import { decodeMultiValue, encodeMultiValue, toggleMultiValue } from '../lib/multiValueFilter';
import { formatPeriodCode, periodOptions } from '../lib/periodOptions';
import { displayPersonName, sentenceCaseData, displayCertificationName } from '../lib/bbvaDisplayFormat';
import type { DashboardHistoricalMetricKey, DashboardMetricComparison } from '../types/dashboard';

interface MetricsFilterState extends Record<string,string> {
  technologyId:string; profileId:string; technologyProfile:string; certificationId:string;
  bbvaStructureLevel2:string; bbvaStructureLevel3:string; quarterCode:string; deliveryManager:string;
  certificationStatus:string; talentType:string; fromDate:string; toDate:string; search:string;
  historyDays:string; comparisonDays:string;
}
const initialFilters:MetricsFilterState={technologyId:'',profileId:'',technologyProfile:'',certificationId:'',bbvaStructureLevel2:'',bbvaStructureLevel3:'',quarterCode:'',deliveryManager:'',certificationStatus:'',talentType:'',fromDate:'',toDate:'',search:'',historyDays:'90',comparisonDays:'7'};
const statusOptions=[{value:'',label:'Todos los estados de certificación'},{value:'VALID',label:'Vigentes'},{value:'EXPIRING',label:'Vencen en el periodo'},{value:'EXPIRED',label:'Vencidas antes del periodo'},{value:'RECERTIFICATION_PENDING',label:'Recertificación pendiente'},{value:'PENDING',label:'Pendientes'},{value:'FAILED',label:'Reprobadas'}];
const universeOptions=[{value:'',label:'Todo el universo'},{value:'ACADEMY',label:'Academia'},{value:'PROSPECT',label:'Prospectos'},{value:'FORMER_COLLABORATOR',label:'Excolaboradores'},{value:'BBVA_EXIT',label:'Bajas de BBVA'}];
function comparisonText(comparison?:DashboardMetricComparison){if(!comparison)return undefined;const sign=comparison.delta>0?'+':'';const unit=comparison.unit==='PERCENTAGE_POINTS'?' pp':'';return `${sign}${comparison.delta.toLocaleString('es-MX',{maximumFractionDigits:2})}${unit} vs ${comparison.previousSnapshotDate}`;}

export const CertificationMetricsPage:React.FC=()=>{
  const navigate=useNavigate();
  const structuresQuery=useStructureOptions();
  const {state:filters,update:updateFilters}=useBBVAListQueryState(initialFilters);
  const [historyMetric,setHistoryMetric]=useState<DashboardHistoricalMetricKey>('coveragePercent');
  const [scoreDetailId,setScoreDetailId]=useState<string|null>(null);
  const [scorePage,setScorePage]=useState(0);const [scoreSize,setScoreSize]=useState(10);
  const [expirationPage,setExpirationPage]=useState(0);const [expirationSize,setExpirationSize]=useState(10);
  const [attentionPage,setAttentionPage]=useState(0);const [attentionSize,setAttentionSize]=useState(10);
  const query=useBbvaDashboard(filters); const data=query.data; const cards=data?.cards;
  const update=(key:keyof MetricsFilterState,value:string)=>updateFilters({[key]:value} as Partial<MetricsFilterState>);
  const quarterOptions=useMemo(()=>periodOptions(data?.vendorQuarter.quarters??[],data?.vendorQuarter.currentCode,data?.vendorQuarter.referenceDate),[data?.vendorQuarter.currentCode,data?.vendorQuarter.quarters,data?.vendorQuarter.referenceDate]);
  const selectedTechnologies=useMemo(()=>decodeMultiValue(filters.technologyId),[filters.technologyId]);
  React.useEffect(()=>{if(data?.vendorQuarter.selectedCode&&!filters.quarterCode)update('quarterCode',data.vendorQuarter.selectedCode);},[data?.vendorQuarter.selectedCode,filters.quarterCode]);
  const filteredContext=Boolean(filters.technologyId||filters.certificationStatus||filters.talentType||filters.bbvaStructureLevel2||filters.bbvaStructureLevel3||filters.certificationId||filters.profileId||filters.technologyProfile);
  const expirationRows=data?.quarterExpirations??[];const safeExpirationPage=Math.min(expirationPage,Math.max(0,Math.ceil(expirationRows.length/expirationSize)-1));
  const scoreRows=(data?.certificationScoreDetails??[]).filter((row)=>row.certificationId===scoreDetailId);const safeScorePage=Math.min(scorePage,Math.max(0,Math.ceil(scoreRows.length/scoreSize)-1));
  const attentionRows=(data?.attention??[]).filter((row)=>row.critical+row.expired+row.recertificationPending+row.expiring+row.pending>0);const safeAttentionPage=Math.min(attentionPage,Math.max(0,Math.ceil(attentionRows.length/attentionSize)-1));
  const technologyBars=useMemo(()=>(data?.technologyDistribution??[]).map((item)=>({key:item.technologyId??'',label:sentenceCaseData(item.label),value:item.value})),[data?.technologyDistribution]);
  const maxTech=Math.max(1,...technologyBars.map((item)=>item.value));
  if(query.error)return <BBVAAlert tone="error">{(query.error as Error).message}</BBVAAlert>;
  return <div className="space-y-3 animate-fade-in">
    <BBVAFilterBar actions={<><BBVAButton variant="secondary" size="sm" icon={<RefreshCw className={`h-3.5 w-3.5 ${query.isFetching?'animate-spin':''}`}/>} onClick={()=>void query.refetch()}>Actualizar</BBVAButton>{(filters.technologyId||filters.certificationStatus||filters.talentType||filters.bbvaStructureLevel2||filters.bbvaStructureLevel3)?<BBVAButton variant="secondary" size="sm" onClick={()=>updateFilters({technologyId:'',certificationStatus:'',talentType:'',bbvaStructureLevel2:'',bbvaStructureLevel3:''})}>Limpiar</BBVAButton>:null}</>}>
      <BBVAMultiSelect className="w-full sm:w-[210px]" values={selectedTechnologies} onChange={(values)=>update('technologyId',encodeMultiValue(values))} options={(data?.filters.technologies??[]).map((item)=>({value:item.id,label:sentenceCaseData(item.name)}))} placeholder="Todas las tecnologías" selectedLabel="tecnologías" ariaLabel="Tecnología"/>
      <div className="w-full sm:w-[190px]"><BBVASearchableSelect value={filters.quarterCode || data?.vendorQuarter.selectedCode || data?.vendorQuarter.currentCode || ''} onChange={(v)=>update('quarterCode',v)} options={quarterOptions} ariaLabel="Periodo" searchPlaceholder="Buscar periodo" emptyMessage="No hay periodos configurados."/></div>
      <div className="w-full sm:w-[180px]"><BBVASearchableSelect value={filters.talentType} onChange={(v)=>update('talentType',v)} options={universeOptions} ariaLabel="Universo"/></div>
      <BBVAStructureFilter className="w-full sm:w-[220px]" items={structuresQuery.data?.items??[]} level2={filters.bbvaStructureLevel2} level3={filters.bbvaStructureLevel3} onChange={(next)=>updateFilters({bbvaStructureLevel2:next.level2,bbvaStructureLevel3:next.level3})} ariaLabel="Estructura BBVA"/>
      <div className="w-full sm:w-[220px]"><BBVASearchableSelect value={filters.certificationStatus} onChange={(v)=>update('certificationStatus',v)} options={statusOptions} ariaLabel="Estado de certificación"/></div>
    </BBVAFilterBar>

    {query.isLoading||!data||!cards?<BBVAMetricsSkeleton cards={5}/>:<>
      <div className="grid grid-cols-[repeat(auto-fit,minmax(180px,1fr))] gap-2">
        <BBVAMetricCard label="Promedio certificaciones" value={cards.certificationAverage??'—'} icon={<Award className="h-4 w-4"/>} tone="blue" help={dashboardMetricDefinitions.certificationAverage} supportingText={`${cards.certificationScoreBase} resultados válidos`}/>
        <BBVAMetricCard label={`Cobertura · ${formatPeriodCode(data.vendorQuarter.selectedCode)}`} value={`${cards.coveragePercent}%`} icon={<ShieldCheck className="h-4 w-4"/>} tone="emerald" help={dashboardMetricDefinitions.coveragePercent} supportingText={data.quarterExpirations.length ? `${data.quarterExpirations.length} vencen en el periodo · ${cards.certificationsApplicable} aplicables` : 'Sin vencimientos en el periodo'} trendText={comparisonText(data.history.comparisons.coveragePercent)}/>
        <BBVAMetricCard label={`Vencen en ${formatPeriodCode(data.vendorQuarter.selectedCode)}`} value={data.quarterExpirations.length} icon={<AlertTriangle className="h-4 w-4"/>} tone={data.quarterExpirations.length?'amber':'emerald'} supportingText="Fechas dentro del periodo" trendText={comparisonText(data.history.comparisons.expiring)} onAction={()=>update('certificationStatus','EXPIRING')} actionLabel="Filtrar"/>
        <BBVAMetricCard label="Pendientes de certificación" value={cards.pending} icon={<CalendarClock className="h-4 w-4"/>} tone={cards.pending?'blue':'emerald'} help={dashboardMetricDefinitions.pending} supportingText={cards.pending?'Requieren cobertura':'Sin pendientes'} trendText={comparisonText(data.history.comparisons.pending)} onAction={()=>update('certificationStatus','PENDING')} actionLabel="Revisar"/>
        <BBVAMetricCard label="Críticos 2/2" value={cards.vendorExitRequired} icon={<UsersRound className="h-4 w-4"/>} tone={cards.vendorExitRequired?'rose':'emerald'} supportingText={`${cards.recertificationPending} recertificaciones`} trendText={comparisonText(data.history.comparisons.vendorExitRequired)} onAction={()=>navigate('/bbva/certifications/tracking?critical=OPEN')} actionLabel="Resolver"/>
      </div>

      <section className="bbva-live-panel overflow-hidden rounded-2xl border border-blue-100 bg-white shadow-sm">
        {data.quarterExpirations.length?<div className="max-h-[300px] overflow-auto"><table className="w-full min-w-[760px] text-left text-[10px]"><thead className="sticky top-0 bg-slate-50 text-[8.5px] font-semibold uppercase text-slate-500"><tr><th className="px-3 py-2">Colaborador</th><th className="px-3 py-2">Certificación</th><th className="px-3 py-2">Vencimiento</th><th className="px-3 py-2 text-right">Acción</th></tr></thead><tbody className="divide-y divide-slate-100">{expirationRows.slice(safeExpirationPage*expirationSize,safeExpirationPage*expirationSize+expirationSize).map((item)=><tr key={`${item.personId}-${item.certificationId}-${item.expirationDate}`} className="hover:bg-blue-50/25"><td className="px-3 py-2 font-semibold">{displayPersonName(item.fullName)}</td><td className="px-3 py-2">{displayCertificationName(item.certificationName)}</td><td className="px-3 py-2 tabular-nums">{item.expirationDate}</td><td className="px-3 py-2 text-right">{item.collaboratorId?<BBVAButton variant="table" size="sm" onClick={()=>navigate(`/bbva/collaborators/${item.collaboratorId}/certifications`)}>Revisar</BBVAButton>:null}</td></tr>)}</tbody></table><BBVAPagination total={expirationRows.length} page={safeExpirationPage} size={expirationSize} onPageChange={setExpirationPage} onSizeChange={(next)=>{setExpirationSize(next);setExpirationPage(0);}}/></div>:<BBVAEmptyState compact title="Sin vencimientos en el periodo" description="No existen certificaciones con fecha de vencimiento dentro del periodo seleccionado."/>}
      </section>

      <section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="border-b border-slate-100 px-4 py-3"><h2 className="text-sm font-semibold text-slate-950">Promedio actual por certificación</h2><p className="mt-0.5 text-[9.5px] text-slate-500">Una calificación válida más reciente por persona y certificación. No pondera intentos adicionales.</p></div><div className="grid gap-2 p-3 sm:grid-cols-2 xl:grid-cols-4">{data.certificationScores.length?data.certificationScores.map((item)=><button key={item.certificationId} type="button" onClick={()=>{setScoreDetailId(scoreDetailId===item.certificationId?null:item.certificationId);setScorePage(0);}} className={`rounded-xl border p-3 text-left transition-colors ${scoreDetailId===item.certificationId?'border-blue-400 bg-blue-50':'border-slate-200 bg-white hover:border-blue-200'}`}><div className="truncate text-[10px] font-semibold text-slate-800">{displayCertificationName(item.certificationName)}</div><div className="mt-2 text-2xl font-semibold tabular-nums text-blue-700">{item.average.toFixed(2)}</div><div className="mt-1 text-[9px] text-slate-500">{item.peopleCount} colaboradores · Ver detalle</div></button>):<div className="col-span-full"><BBVAEmptyState compact title="Sin calificaciones válidas" description="No existen calificaciones configuradas para el universo y filtros actuales."/></div>}</div>{scoreDetailId?<div className="border-t border-slate-100 p-3"><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-[10px]"><thead className="bg-slate-50 text-[8.5px] uppercase text-slate-500"><tr><th className="px-3 py-2">Colaborador</th><th className="px-3 py-2">Resultado</th><th className="px-3 py-2 text-center">Calificación</th><th className="px-3 py-2">Fecha</th><th className="px-3 py-2 text-center">Intento</th></tr></thead><tbody className="divide-y divide-slate-100">{scoreRows.slice(safeScorePage*scoreSize,safeScorePage*scoreSize+scoreSize).map((row)=><tr key={`${row.personId}-${row.certificationId}`}><td className="px-3 py-2 font-medium">{displayPersonName(row.fullName)}</td><td className="px-3 py-2">{sentenceCaseData(row.result)}</td><td className="px-3 py-2 text-center font-semibold">{row.score10.toFixed(2)}</td><td className="px-3 py-2">{row.applicationDate??'—'}</td><td className="px-3 py-2 text-center">{row.attemptNumber??'—'}</td></tr>)}</tbody></table></div><BBVAPagination total={scoreRows.length} page={safeScorePage} size={scoreSize} onPageChange={setScorePage} onSizeChange={(next)=>{setScoreSize(next);setScorePage(0);}}/></div>:null}</section>

      <div className="grid gap-3 xl:grid-cols-2"><BBVAChartCard title={`Distribución tecnológica · ${formatPeriodCode(data.vendorQuarter.selectedCode)}`} description="Selecciona una tecnología para actualizar el universo."><BBVAHorizontalBars items={technologyBars} max={maxTech} selectedKey={selectedTechnologies.length===1?selectedTechnologies[0]:''} onSelect={(id)=>update('technologyId',toggleMultiValue(filters.technologyId,id))}/></BBVAChartCard>{!filteredContext?<BBVAHistoricalMetricPanel history={data.history} metric={historyMetric} onMetricChange={setHistoryMetric} allowedMetrics={['coveragePercent','expiring','expired','recertificationPending','pending','vendorReadyPercent','vendorPending','vendorExitRequired']} title={`Evolución histórica · ${formatPeriodCode(data.vendorQuarter.selectedCode)}`}/>:<BBVAChartCard title="Histórico del periodo" description="El histórico sólo compara snapshots del mismo periodo y del universo global."><BBVAEmptyState compact title="Quita filtros para comparar" description="Así evitamos comparar universos distintos."/></BBVAChartCard>}</div>

      <div className="flex justify-end"><BBVAButton variant="table" size="sm" onClick={()=>navigate('/bbva/certifications/tracking')}>Seguimiento</BBVAButton></div><section className="overflow-hidden rounded-2xl border border-slate-200 bg-white shadow-sm"><div className="overflow-x-auto"><table className="w-full min-w-[980px] text-left text-[10px]"><thead className="bg-slate-50 text-[8.5px] font-semibold uppercase text-slate-500"><tr><th className="px-3 py-2">Colaborador</th><th className="px-3 py-2">Tecnología</th><th className="px-3 py-2">Estructura nivel 2</th><th className="px-3 py-2">Estructura nivel 3</th><th className="px-3 py-2 text-center">Próximas</th><th className="px-3 py-2 text-center">Pendientes</th><th className="px-3 py-2 text-right">Acción</th></tr></thead><tbody className="divide-y divide-slate-100">{attentionRows.slice(safeAttentionPage*attentionSize,safeAttentionPage*attentionSize+attentionSize).map((row)=><tr key={row.collaboratorId} className="hover:bg-slate-50"><td className="px-3 py-2"><div className="font-semibold">{displayPersonName(row.fullName)}</div><div className="text-[9px] text-slate-400">{sentenceCaseData(row.profile)}</div></td><td className="px-3 py-2">{sentenceCaseData(row.technology)}</td><td className="px-3 py-2">{sentenceCaseData(row.bbvaStructureLevel2)}</td><td className="px-3 py-2">{sentenceCaseData(row.bbvaStructureLevel3)}</td><td className="px-3 py-2 text-center font-semibold text-amber-700">{row.expiring}</td><td className="px-3 py-2 text-center font-semibold text-blue-700">{row.pending}</td><td className="px-3 py-2 text-right"><BBVAButton variant="table" size="sm" onClick={()=>navigate(`/bbva/collaborators/${row.collaboratorId}/certifications`)}>Revisar</BBVAButton></td></tr>)}</tbody></table></div><BBVAPagination total={attentionRows.length} page={safeAttentionPage} size={attentionSize} onPageChange={setAttentionPage} onSizeChange={(next)=>{setAttentionSize(next);setAttentionPage(0);}}/></section>
    </>}
  </div>;
};
