import { app,HttpRequest,HttpResponseInit,InvocationContext } from '@azure/functions';
import { getCurrentUser } from '../lib/authzLocal.js';import { assertBbvaPermission } from '../lib/bbvaAuthz.js';import { readBbvaJson } from '../lib/bbvaHttp.js';import { BbvaEngineeringSpecialtyService } from '../lib/bbvaEngineeringSpecialtyService.js';
const service=new BbvaEngineeringSpecialtyService();const fail=(e:unknown,c:InvocationContext):HttpResponseInit=>{const x=e as any;c.error('[BBVA:EngineeringSpecialties]',x?.message||e);if(x?.statusCode)return{status:x.statusCode,jsonBody:{error:x.message}};if(x?.number===2601||x?.number===2627)return{status:409,jsonBody:{error:'La especialidad ya existe dentro del mismo gremio.'}};return{status:500,jsonBody:{error:'No fue posible completar la operación.'}}};
async function collection(req:HttpRequest,ctx:InvocationContext):Promise<HttpResponseInit>{try{const u=getCurrentUser(req);if(req.method==='GET'){assertBbvaPermission(u,'CATALOG_READ');return{status:200,jsonBody:await service.list(req.query.get('search')??'',(req.query.get('status')??'ACTIVE') as any,Number(req.query.get('page')??0),Number(req.query.get('size')??10))};}assertBbvaPermission(u,'CATALOG_WRITE');return{status:201,jsonBody:{item:await service.create(await readBbvaJson(req),u.email)}};}catch(e){return fail(e,ctx)}}
async function item(req:HttpRequest,ctx:InvocationContext):Promise<HttpResponseInit>{try{const u=getCurrentUser(req),id=req.params.id;if(!id)return{status:400,jsonBody:{error:'ID requerido.'}};if(req.method==='GET'){assertBbvaPermission(u,'CATALOG_READ');const v=await service.get(id);return v?{status:200,jsonBody:{item:v}}:{status:404,jsonBody:{error:'Especialidad no encontrada.'}};}assertBbvaPermission(u,'CATALOG_WRITE');const v=await service.update(id,await readBbvaJson(req),u.email);return v?{status:200,jsonBody:{item:v}}:{status:404,jsonBody:{error:'Especialidad no encontrada.'}};}catch(e){return fail(e,ctx)}}
async function status(req:HttpRequest,ctx:InvocationContext):Promise<HttpResponseInit>{try{const u=getCurrentUser(req);assertBbvaPermission(u,'CATALOG_WRITE');const v=await service.status(req.params.id,(await readBbvaJson(req))?.status,u.email);return v?{status:200,jsonBody:{item:v}}:{status:404,jsonBody:{error:'Especialidad no encontrada.'}};}catch(e){return fail(e,ctx)}}
app.http('bbvaEngineeringSpecialtyCollection',{methods:['GET','POST'],authLevel:'anonymous',route:'bbva/engineering-specialties',handler:collection});
app.http('bbvaEngineeringSpecialtyItem',{methods:['GET','PUT'],authLevel:'anonymous',route:'bbva/engineering-specialties/{id}',handler:item});
app.http('bbvaEngineeringSpecialtyStatus',{methods:['PATCH'],authLevel:'anonymous',route:'bbva/engineering-specialties/{id}/status',handler:status});
