import { app, HttpRequest, HttpResponseInit, InvocationContext } from '@azure/functions';
import { getCurrentUser } from '../lib/authzLocal.js';
import { assertBbvaPermission } from '../lib/bbvaAuthz.js';
import { readBbvaJson } from '../lib/bbvaHttp.js';
import { BbvaStructureCatalogService } from '../lib/bbvaStructureCatalogService.js';
const service=new BbvaStructureCatalogService();
const failure=(e:unknown,c:InvocationContext):HttpResponseInit=>{const x=e as {message?:string;statusCode?:number;number?:number};c.error('[BBVA:Structures]',x?.message||e);if(x?.statusCode)return{status:x.statusCode,jsonBody:{error:x.message}};if(x?.number===2601||x?.number===2627)return{status:409,jsonBody:{error:'Ya existe una estructura con ese nombre y nivel.'}};return{status:500,jsonBody:{error:'No fue posible completar la operación de estructuras.'}};};
export async function collection(req:HttpRequest,ctx:InvocationContext):Promise<HttpResponseInit>{try{const user=getCurrentUser(req);if(req.method==='GET'){assertBbvaPermission(user,'CATALOG_READ');return{status:200,jsonBody:{items:await service.list(req.query.get('search')??'',(req.query.get('status')??'ACTIVE') as any)}};}assertBbvaPermission(user,'CATALOG_WRITE');return{status:201,jsonBody:{item:await service.create(await readBbvaJson(req),user.email)}};}catch(e){return failure(e,ctx);}}
export async function options(req:HttpRequest,ctx:InvocationContext):Promise<HttpResponseInit>{try{const user=getCurrentUser(req);assertBbvaPermission(user,'CATALOG_READ');return{status:200,jsonBody:{items:await service.options()}};}catch(e){return failure(e,ctx);}}
export async function item(req:HttpRequest,ctx:InvocationContext):Promise<HttpResponseInit>{try{const user=getCurrentUser(req);const id=req.params.id;if(!id)return{status:400,jsonBody:{error:'ID requerido.'}};if(req.method==='GET'){assertBbvaPermission(user,'CATALOG_READ');const value=await service.get(id);return value?{status:200,jsonBody:{item:value}}:{status:404,jsonBody:{error:'Estructura no encontrada.'}};}assertBbvaPermission(user,'CATALOG_WRITE');if(req.method==='PUT'){const value=await service.update(id,await readBbvaJson(req),user.email);return value?{status:200,jsonBody:{item:value}}:{status:404,jsonBody:{error:'Estructura no encontrada.'}};}if(req.method==='DELETE')return{status:200,jsonBody:{deleted:await service.delete(id)}};return{status:405};}catch(e){return failure(e,ctx);}}
export async function status(req:HttpRequest,ctx:InvocationContext):Promise<HttpResponseInit>{try{const user=getCurrentUser(req);assertBbvaPermission(user,'CATALOG_WRITE');const id=req.params.id;if(!id)return{status:400,jsonBody:{error:'ID requerido.'}};const body=await readBbvaJson(req);const value=await service.status(id,body?.status,user.email);return value?{status:200,jsonBody:{item:value}}:{status:404,jsonBody:{error:'Estructura no encontrada.'}};}catch(e){return failure(e,ctx);}}
app.http('bbvaStructureCollection',{methods:['GET','POST'],authLevel:'anonymous',route:'bbva/structures',handler:collection});
app.http('bbvaStructureOptions',{methods:['GET'],authLevel:'anonymous',route:'bbva/structure-options',handler:options});
app.http('bbvaStructureItem',{methods:['GET','PUT','DELETE'],authLevel:'anonymous',route:'bbva/structures/{id}',handler:item});
app.http('bbvaStructureStatus',{methods:['PATCH'],authLevel:'anonymous',route:'bbva/structures/{id}/status',handler:status});
